### ISSUE TITLE
SVG rect click results in error

### ISSUE THREAD

**Issue by Mardaneus86** [mixpanel/mixpanel-js#105]
I'm implementing a C3.js chart component in my website which is based on SVG rendering. Whenever I click this chart a MixPanel event fires, but this results in an error ```Mixpanel error: Implementation error. Please contact support@mixpanel.com.```. 

The underlying problem is that this line: https://github.com/mixpanel/mixpanel-js/blob/6faaecaabb6ca9fe7c4f0a64c7dd5cb893adbfae/src/ce.js#L313 expects to get normal class names, but in this case it receives an ```SVGAnimatedString``` object because https://github.com/mixpanel/mixpanel-js/blob/6faaecaabb6ca9fe7c4f0a64c7dd5cb893adbfae/src/ce.js#L39 only checks for ```svg```. In my case the tagName is ```rect```, and it could potentially be any of the svg elements.

Would it be feasible to check if ```elem.className``` is a string or an object, and if it's an object to return the ```elem.className.baseVal```?

**Comment by tdumitrescu** [comment]
Hi @Mardaneus86, thanks for the report and sorry for the delayed response. This issue should be fixed in [v2.9.15](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.9.15) released last week. Please don't hesitate to reopen if the problem persists!

**Comment by Mardaneus86** [comment]
Great. Going to try it!
