### ISSUE TITLE
Refused to get unsafe header "X-MP-CE-Backoff" with Service Worker

### ISSUE THREAD

**Issue by danii1** [mixpanel/mixpanel-js#111]
Can be reproduced with https://github.com/TalAter/UpUp and mixpanel-browser 2.9.16, requests are going through Service Worker, I'm getting this error:
<img width="394" alt="2016-11-26 9 52 43" src="https://cloud.githubusercontent.com/assets/5345961/20649941/385ca332-b4e4-11e6-8393-b1f2f960c46d.png">

**Comment by tdumitrescu** [comment]
Do you have browser/OS info? Anything in https://github.com/mixpanel/mixpanel-js/issues/92 help?

**Comment by NitroBAY** [comment]
Same problem, did @danii1 you solve the issue ?

**Comment by jbwyme** [comment]
@NitroBAY can you let us know what browser and version you're seeing this on? We are setting `Access-Control-Expose-Headers: 'X-MP-CE-Backoff'` in the response which _should_ allow the client to read the header. However, I've read that there are cases where this behavior is buggy in certain browser/versions.

**Comment by danii1** [comment]
I've tested in recent Chrome, I believe the same issue will be in Firefox, happens because Service Worker is proxying requests. Should be easy to reproduce to adding UpUp(or installing your own Service Worker) and trying to send something to Mixpanel, #92 is unrelated to this issue.

**Comment by NitroBAY** [comment]
I'm also having this issue in chrome 56

**Comment by NitroBAY** [comment]
Any known workaround ? @danii1 how did you do these past 3 months ?

**Comment by NitroBAY** [comment]
Besides, even tough it's a kinda newbie question, from what spec the value "X-MP-CE-Backoff" is coming from ? When I search for this I only find people complaining about having this issue with Mixpanel ?

**Comment by danii1** [comment]
@NitroBAY there's no workaround, this needs proper fix. We just tested Service Worker related stuff in our product and noticed issue related to Mixpanel tracking. We have other things in priority for now and don't install service workers/provide offline functionality, but this will be a problem when we do.

**Comment by jbwyme** [comment]
Alright we're going to remove this code for now to solve the issue you all are seeing. I'll try to have a release shipped by the end of the week.

**Comment by NitroBAY** [comment]
@jbwyme great but what spec/doc did you have based on ? Where does "X-MP-CE-Backoff" is coming from ?

**Comment by tdumitrescu** [comment]
It's a [custom header](https://www.safaribooksonline.com/library/view/restful-web-services/9780596809140/ch01s13.html).

**Comment by NitroBAY** [comment]
Okay thanks.

**Comment by jbwyme** [comment]
It's a custom header so we also send a header on the response "access-control-expose-headers" which is _supposed_ to allow

**Comment by jbwyme** [comment]
Merged and released (v2.11.0)
