### ISSUE TITLE
2.9.17 crashes our website with Infinite callstack

### ISSUE THREAD

**Issue by ebdrup** [mixpanel/mixpanel-js#115]
![image](https://cloud.githubusercontent.com/assets/899914/21045511/fd9c60e0-be00-11e6-96f3-d3e497727bad.png)

We had to disable the script to get the site back.

How do we lock the version of the script that we use? What is the supported way of locking version, instead of loading latest?

**Comment by bubenshchykov** [comment]
+1 :(

**Comment by ebdrup** [comment]
Apparently this was caused by the script added twice on our end.

**Comment by tdumitrescu** [comment]
@ebdrup so it wasn't related to the 2.9.17 release then? @bubenshchykov is your case different?

If you want to lock down the library to a specific patch version, the recommended options right now are installation via NPM or installation via Bower. See the sections starting here: https://github.com/mixpanel/mixpanel-js#alternative-installation-via-npm

**Comment by bubenshchykov** [comment]
@tdumitrescu that was my case as well - library loaded twice, by mistake. I think you can close the issue

**Comment by ebdrup** [comment]
You you can close it. Sorry for the false alarm.
