### ISSUE TITLE
/decide still goes directly to api.mixpanel.com when using api_host config

### ISSUE THREAD

**Issue by rarkins** [mixpanel/mixpanel-js#118]
When specifying my own host using the `api_host` parameter, I am seeing `/track` and `/engage` messages go to the new host, but `/decide` still goes directly to `api.mixpanel.com`.

**Comment by tdumitrescu** [comment]
Thanks for the report. Looks like there's now a [`decide_host` config entry](https://github.com/mixpanel/mixpanel-js/blob/b4cf2c5cb900fbb102370c01553e9a70f4c6e2d0/src/mixpanel-core.js#L1571) that needs to be set. My feeling is that `decide_host` really ought to be just be an override of `api_host` (i.e., that setting just `api_host` and not touching `decide_host` should Do The Right Thing and use the custom `api_host` for decide requests as well), but right now it doesn't do that; `decide_host` [defaults to the _default_ api host](https://github.com/mixpanel/mixpanel-js/blob/b4cf2c5cb900fbb102370c01553e9a70f4c6e2d0/src/mixpanel-core.js#L112), even if the user has overridden it.

@jbwyme how would you feel about the change I describe here? @rarkins in the meanwhile, you can set `decide_host` in your config to get around this.

**Comment by rarkins** [comment]
@tdumitrescu I can confirm that adding `decide_host` fixes the problem. However I agree with you that it would be nicest if `decide_host` defaulted to the value of `api_host`.

**Comment by jbwyme** [comment]
TBH I don't remember off the top of my head why it got separated. I know that it had to mostly do with development and I can't think of a solid reason why it would be useful for a customer to override one and not the other so my vote is we just get rid of `decide_host` and re-think it if we need to in the future.

**Comment by jbwyme** [comment]
v2.12.0 removes `decide_host` completely and relies on `api_host` which should solve your issue here. Thanks!

**Comment by wireed-in** [comment]
Hi @jbwyme and @rarkins 

We are facing issues with Content Security Policy and mixpanel making requests to https://api.mixpanel.com since we have a pretty strict CSP and not allowing outside requests.

Could you please point me to some resources how we can completely self host mixpanel? Thanks.

**Comment by tdumitrescu** [comment]
@wireed-in that's a big question with a lot of implementation details specific to your company's needs and setup. You'd be best off getting in touch with support@mixpanel.com to figure out what will work for you.

**Comment by wireed-in** [comment]
@tdumitrescu thanks for the advice. I have already contacted support@mixpanel.com but haven't gotten a response back. While waiting I wanted to explore alternative channels and see if anyone can point me to some resources who have faced the same issue.
