### ISSUE TITLE
Disable / configure reading from hash

### ISSUE THREAD

**Issue by sorin-davidoi** [mixpanel/mixpanel-js#124]
I'm using Mixpanel in conjunction with Auth0 Lock and I'm encountering a problem right after user authentication. Auth0 redirects the user to my homepage, passing authentication tokens in the hash. One of the parameters is called `state`, which apparently Mixpanel tries to use to load the editor, throwing errors in the process.

Right now I'm working around this by applying a patch which disables [reading from the hash](https://github.com/mixpanel/mixpanel-js/blob/master/build/mixpanel.cjs.js#L1994), but I was wondering if there should be a flag which disables this behaviour (especially since it seams that it is only used by some legacy versions?).

**Comment by jbwyme** [comment]
We shipped a new version that should fix your issue. Please update to v2.12.0 and confirm if it is indeed solved. Thanks!

**Comment by sorin-davidoi** [comment]
Can't test this anymore but I'll close it anyway. Thanks!
