### ISSUE TITLE
Getting 414 error (Request URI Too Long)

### ISSUE THREAD

**Issue by crk4** [mixpanel/mixpanel-js#136]
When mixpanel.track method has been called two continuous requests has been triggered and one is failed by getting the 414 response status code another one request is successfully getting 200 response code.  

below is the error reported in the console. Please note that at the end its says something related to CORS issue. please help.

GET https://api.mixpanel.com/track/?data=eyJldmVudCI6ICIk.............YwMDYxOTRlOTcwN2ZiZjQ0OTMxYzBlYzAiLCIkX19jIjogMX19&ip=1&_=1502975377922 414 (Request URI Too Long)
h.p @ mixpanel-2-latest.min.js:64
h.I @ mixpanel-2-latest.min.js:68
Lc @ mixpanel-2-latest.min.js:45
(anonymous) @ mixpanel-2-latest.min.js:13
(anonymous) @ mixpanel-2-latest.min.js:45
Default.aspx?tid=3:1 XMLHttpRequest cannot load https://api.mixpanel.com/track/?data=eyJldmVudCI6.............YmM2OTkyYWYwMDYxOTRlOTcwN2ZiZjQ0OTMxYzBlYzAiLCIkX19jIjogMX19&ip=1&_=1502975377922. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:21228' is therefore not allowed access. The response had HTTP status code 414.

**Comment by wgins** [comment]
Hey @crk4 thanks for the report! 

Would you mind writing into support@mixpanel.com with these details? Our Support Engineering team can take a closer look at where this request is being made and point you in the right direction.

**Comment by crk4** [comment]
@wgins thanks for your reply, will send a mail to mixpanel support

**Comment by tdumitrescu** [comment]
Thanks, will close this out. Please reopen if there's a lib code issue.

**Comment by jbwyme** [comment]
I'm pretty sure this is related to Autotrack event selectors. We need to
migrate to making POST requests.
