### ISSUE TITLE
Grab browser version as a super property automatically

### ISSUE THREAD

**Issue by orienwu** [mixpanel/mixpanel-js#14]
Helps isolate browser version specific behavior / issues.

**Comment by D1plo1d** [comment]
+1 browser versions would be useful for me in deciding which browsers to support (eg. we need compatibility for ie 9 and 10 but not 8 because no one on our site uses it anymore).

**Comment by nirradian** [comment]
+1 This seems trivial to collect - this should be in there

**Comment by cgarvis** [comment]
+1

**Comment by shakefu** [comment]
+1

**Comment by tdumitrescu** [comment]
Hi all, we do plan on supporting this at some point; if you want to expedite the process, the best way is to open a pull request!

**Comment by D1plo1d** [comment]
@tdumitrescu One pull request ready and waiting for review. Hope it helps! :)

**Comment by tdumitrescu** [comment]
Added in v2.5.1 (thanks @D1plo1d)

**Comment by D1plo1d** [comment]
@tdumitrescu Cheers!
