### ISSUE TITLE
Return Mixpanel reference on loaded event

### ISSUE THREAD

**Issue by bennyn** [mixpanel/mixpanel-js#142]
There is the following Mixpanel initialization:

```javascript
mixpanel.init("FAKE_TOKEN", {
  debug: true,
  loaded: function () {
    console.log("Mixpanel loaded successfully");
  }
});
```

It would be great if the `loaded` event could return a Mixpanel instance, so that an external callback can interact with Mixpanel like:

```javascript
function onLoaded(mixpanel) {
  mixpanel.register_once({"ad_campaign": "fb-01"});
}

mixpanel.init("FAKE_TOKEN", {
  debug: true,
  loaded: onLoaded
});
```

**Comment by jaredmixpanel** [comment]
Hi @bennyn, it does in fact.  Your example using register_once is perfectly valid.

**Comment by jaredmixpanel** [comment]
Examples:

https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.get_distinct_id

https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.get_property

**Comment by bennyn** [comment]
I must have missed that from the documentation. Great that you have this callback property! 🤗
