### ISSUE TITLE
current API SSL certificate won't be supported anymore in the version 70 of Chrome

### ISSUE THREAD

**Issue by polco** [mixpanel/mixpanel-js#147]
I get this warning in chrome canary
```
The SSL certificate used to load https://api.mixpanel.com/track/?data=*** will be distrusted in M70. Once distrusted, users will be prevented from loading this resource. See https://g.co/chrome/symantecpkicerts for more information.
```

**Comment by dgpc** [comment]
Hi @polco, indeed we are tracking this issue with our internal issue tracker, and I can assure you we will rotate our TLS certificate before March 5 2018 when Chrome Beta will stop trust our current certificate. Thanks!

**Comment by tdumitrescu** [comment]
We'll keep this issue open and close it out once the cert is replaced for visibility.

**Comment by varrunramani-okta** [comment]
@polco Do you have an update on when the certificate is going to be renewed?

**Comment by dgpc** [comment]
@varrunramani-okta - we expect to have replacement certificates live this month (Jan 2018).

**Comment by dgpc** [comment]
New certificates have been deployed for mixpanel.com, and its subdomains.
New certs for the CDN domain, mxpnl.com, coming soon.

**Comment by wolfmaster8** [comment]
Hello. I'm getting this error in Chrome 64: 

> The SSL certificate used to load resources from https://cdn.mxpnl.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

I've not been able to see any stats in Mixpanel. It stills says: WE HAVEN'T RECEIVED ANY EVENTS FROM YOU YET.
More than 200 persons have entered the webpage today.

**Comment by samanthagmccormick** [comment]
@wolfmaster8  I believe @dgpc  said that new certificates for mxpnl.com are coming soon. So we will still see that message until that happens (I see it too).

**Comment by tdumitrescu** [comment]
@wolfmaster8 the existing certificate is not yet distrusted, which makes it very unlikely that your integration problem is related. Please write to support@mixpanel.com and they can help you track down why you're not seeing events.

**Comment by tdumitrescu** [comment]
Both api.mixpanel.com and cdn.mxpnl.com have had updated certs for a little while now, so this warning should be completely gone now. I'm going to close this issue out; feel free to reopen/comment if anyone is still seeing cert-related warnings.
