### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by johnpaulmanoza** [mixpanel/mixpanel-js#149]
The js file has an error when using in Safari version 9 and below.

**Comment by tdumitrescu** [comment]
Can you give us some more specific information? What is the exact error you're getting, and which OS? We do test the lib across a matrix of browsers including Safari 9 and haven't been able to reproduce. If you'd prefer to go over your configuration with 1-on-1 support, please write in to support@mixpanel.com.

**Comment by tdumitrescu** [comment]
I'm going to close this out as stale / can't reproduce. Feel free to reopen with more info, or go over your case with support@mixpanel.com, thanks!
