### ISSUE TITLE
mixpanel.identify() not working

### ISSUE THREAD

**Issue by vincentleeuwen** [mixpanel/mixpanel-js#150]
I've just set up the library, and while .init() and .track() work fine, I don't get any data in when I try to identify users in my React app:

```
mixpanel.init('SOME_API_KEY');
mixpanel.identify('test@user.com');
```

After running this in componentDidMount, there's still no new datapoint: https://www.dropbox.com/s/x1zeedfiya52vl9/Screenshot%202017-10-26%2016.55.54.png?dl=0. Same problem for `mixpanel.alias()`.

What do I do wrong?

**Comment by EmptyCrown** [comment]
I'm getting this issue as well. Did you end up figuring it out @vincentleeuwen?

**Comment by trevor-ofarrell** [comment]
Any resolution?
