### ISSUE TITLE
What's the return value of mixpanel.track callback?

### ISSUE THREAD

**Issue by bennyn** [mixpanel/mixpanel-js#158]
I was reading the documentation on [`mixpanel.track`](https://mixpanel.com/help/reference/javascript#sending-events) and noticed that you can supply a callback, like:

```js
new Promise(resolve => mixpanel.track(event.name, event.attributes, a => resolve(a)))
```

I wanted to know what `a` is, so I logged it and it returned `1`. But what's the intention of that `1`?

**Comment by jaredmixpanel** [comment]
@bennyn "Each event you record is represented as a JSON object in a request to http://api.mixpanel.com/track/. The request will return an HTTP response with body "1" if the track call is successful, and a "0" otherwise."

Source: https://mixpanel.com/help/reference/http#tracking-events

**Comment by bennyn** [comment]
Thanks @jaredmixpanel! 👍
