### ISSUE TITLE
Error when tracking an event with % in URL query param for any of: utm_source utm_medium utm_campaign utm_content utm_term

### ISSUE THREAD

**Issue by jsvg** [mixpanel/mixpanel-js#159]
### Steps to reproduce

1. Create a project with mixpanel-js
2. Navigate to localhost:port/?utm_term=foo%bar
3. Fire a track page event
4. Get this error:

![screen shot 2017-11-29 at 12 50 12 pm](https://user-images.githubusercontent.com/15639838/33390452-e9c45580-d503-11e7-9f15-87cad3d41abc.png)

The error appears to originate in this block
![image](https://user-images.githubusercontent.com/15639838/33390711-c09dc406-d504-11e7-9bb1-80208a051be6.png)

Looking at `mixpanel.cjs.js`

Stepping into the `getQueryParam` function, get to:
`return decodeURIComponent(results[1]).replace(/\+/g, ' ');`

Where `decodeURIComponent('foo%bar')` will be executed, causing the `Uncaught URIError: URI malformed` to throw.

Changing `decodeURIComponent(...)` to `decodeURIComponent(encodeURIComponent(...))` seems to fix the issue, however, not sure if this best approach, or if I should try to fix the issue upsteam.

![image](https://user-images.githubusercontent.com/15639838/33391066-e4555a0c-d505-11e7-91a8-af1529e162b7.png)

**Comment by mjohnston-pm** [comment]
Are there any plans to fix this?  We are currently experiencing this issue and it is causing a crash.

**Comment by tdumitrescu** [comment]
The lib should definitely be fixed not to throw an exception, though the exact behavior it should exhibit when it receives a malformed URI component like this is unclear. In the case of `?utm_term=foo%bar`, I'm inclined to leave the original string untouched when creating the event property (`"foo%bar"`) rather than run it through `encodeURIComponent` as suggested above (`"foo%25bar"`).

**Comment by mjohnston-pm** [comment]
That should address the error, but encoding an already-encoded URI component will encode the % characters.

Let's say you wanted to use `utm_term=abc&def` in a URL which you encode to `utm_term=abc%26def`,
When the code runs it will encode it to `utm_term=abc%2526def` then decode it back to `utm_term=abc%26def`

Is it valid to return the string unchanged if it can't be decoded?

**Comment by tdumitrescu** [comment]
Yeah the problem with unconditionally encoding then decoding is that it defeats actual correct encoding on the URL. For instance if you go to `localhost:port/?utm_term=abc%26def`, that _should_ set the property as "abc&def" but `decodeURIComponent(encodeURIComponent('abc%26def'))` would store it incorrectly as "abc%26def".

**Comment by tdumitrescu** [comment]
Proposed fix is at https://github.com/mixpanel/mixpanel-js/pull/235

**Comment by tdumitrescu** [comment]
Fixed in v2.32.0
