### ISSUE TITLE
setup Test environment when working on localhost

### ISSUE THREAD

**Issue by gamegee** [mixpanel/mixpanel-js#162]
Hi,

I would like to put mixpanel in test mode, then all the events sent when testing on localhost dont mix with the production data on Mixpanel.

If there is no test mode, what is the best way handle that?

**Comment by cassiegamm** [comment]
Hi @gamegee,

Keeping production data clean in Mixpanel is important. I'd recommend creating two projects, one for production data and another for development. After creating a development project, you can refer to the example in this [article](https://mixpanel.com/blog/2014/07/28/automatically-separate-development-data/ ) to separate your production and development project data automatically.
