### ISSUE TITLE
[SECURITY CONCERN] mixpanel autotracking password field 

### ISSUE THREAD

**Issue by ncphillips** [mixpanel/mixpanel-js#164]
We received an email from the Mixpanel Security Team informing us that the auto-track feature was tracking the password field. They suggested updating to the latest version of but I can't find any record of that being addressed in this repository. Can anyone confirm if this vulnerability affected the javascript library as well as the mobile SDKs?

**Comment by jonmcclintock** [comment]
Thanks for reaching out. We're in the process of releasing that change now, sorry for the delay.

**Comment by jonmcclintock** [comment]
We've just released version 2.16.0, which contains the fix. Thanks for your patience.

**Comment by jonmcclintock** [comment]
Also, to clarify: the issue only affects the JS SDK, and not the mobile SDKs.

**Comment by joealcorn** [comment]
Any word when this will be available on npm?

**Comment by zakj** [comment]
@joealcorn Available on NPM now.

**Comment by joealcorn** [comment]
Excellent, thank you
