### ISSUE TITLE
_.JSONDecode throws a raw object instead of a proper error on failure

### ISSUE THREAD

**Issue by pkaminski** [mixpanel/mixpanel-js#169]
The `_.JSONDecode` function signals errors by throwing a raw object:  https://github.com/mixpanel/mixpanel-js/blob/master/src/utils.js#L533.  This is bad practice, as the thrown object won't have a stack trace to help track down its origin and can mess up downstream exception-tracking libraries.  Please throw a `new Error` (or a subclass) instead.

**Comment by tdumitrescu** [comment]
Thanks for the report, we'll get it on the backlog. If you want to help expedite the fix, Pull Requests are always welcome!

**Comment by pkaminski** [comment]
OK, proposed fix in https://github.com/mixpanel/mixpanel-js/pull/170.
