### ISSUE TITLE
Support for sending analytics data using Beacon API

### ISSUE THREAD

**Issue by myylow** [mixpanel/mixpanel-js#171]
Would you consider supporting sending data using the Beacon API https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API as an option?  Browser support is pretty good nowadays https://caniuse.com/#search=beacon.

It lets analytics data be sent reliably even while a user is leaving the page. It’s perfect for tracking clicks on links, without the delay/lost data tradeoff of the track_links function. It would also be easier for sending the events, we wouldn’t have to think about whether to call track/track_links/track_forms and whether the links exist on the page at the time the function is called.

I think an ideal implementation would be how Google Analytics does it, where the library will send the analytics data using the Beacon API if available and fallback to an alternative if not. It would be great if Mixpanel had something similar. Thanks!

**Comment by blord-fullscreen** [comment]
A couple further points:

1) UPDATE The Beacon API is now supported in all modern browsers, including iOS. This is the modern standard for reporting analytics data asynchronously.

2) 300ms (plus or minus) per tracked click really adds up over time. And even for a short interaction, the UX cost of a laggy interface is steep. It’s really worth the engineering effort. Google engineers worked to remove the 300ms delay for touchscreen double-tap back in 2013 for the same reasons. There's plenty of ways to do the math. For example: over a million clicks, a 300ms delay adds up to over eighty hours of your user's time.

We would love to see Mixpanel implement this. If there are no plans to implement this, we'd like to know that, too. Can we get a response from the team on this?

**Comment by kulanjith-deelaka-appspotr** [comment]
Any update on this?

**Comment by tdumitrescu** [comment]
Sorry, should have closed this issue out when the original release went out! Beacon API support landed in [v2.33.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.33.0) in early 2020.
