### ISSUE TITLE
Add Headers to Requests for Authentication

### ISSUE THREAD

**Issue by austince** [mixpanel/mixpanel-js#173]
Hi all,

Is there a way to add authorization headers to the XHR requests? I'd like to proxy all mixpanel api calls through my api but add authorization.

Thanks!

**Comment by austince** [comment]
Also: would you accept a PR that exposed this functionality?

**Comment by tdumitrescu** [comment]
Sure, a configuration option that lets you add auth headers to requests sounds like it'd be useful!

**Comment by austince** [comment]
Awesome, I'll put something in next week!

**Comment by tdumitrescu** [comment]
Fixed in https://github.com/mixpanel/mixpanel-js/pull/175
