### ISSUE TITLE
Where is distinct_id stored in cookies?

### ISSUE THREAD

**Issue by cqcn1991** [mixpanel/mixpanel-js#176]
I can get distinct_id through console, 
![qq 20180426234349](https://user-images.githubusercontent.com/2425141/39316453-c83cd4c4-49ab-11e8-89f1-0a56b03a6c49.png)
but when I see the cookie, I didn't find anything revelant to Mixpanel
![qq 20180426234419](https://user-images.githubusercontent.com/2425141/39316475-d6162564-49ab-11e8-8616-121b5bdeffd0.png)

I want to know where is the distinct_id?

Thanks!

**Comment by tdumitrescu** [comment]
You want the cookie named `mp_<YOURTOKEN>_mixpanel`.

**Comment by cqcn1991** [comment]
@tdumitrescu I'm sorry, but I really didn't see it. But I can access it through `mixpanel.get_distinct_id()`. The pic you see is the cookie for all (GA, Amplitude, Segment, but no mixpanel). 

![qq 20180505094618](https://user-images.githubusercontent.com/2425141/39658592-3335411e-5049-11e8-8f43-b3f6582f89b4.png)

I really have no idea why this is happening.... My app is at http://learnbyreading.herokuapp.com/

**Comment by jaredmixpanel** [comment]
@cqcn1991 The Mixpanel cookie (by default) is a cross-subdomain cookie. Heroku does not allow cross-subdomain cookies. 

Change the cross_subdomain_cookie config setting in your mixpanel.init function to false, which will allow your subdomain's cookie to be stored and keep the Mixpanel distinct_id consistent across the sub-domain:

`mixpanel.init(PROJECT_TOKEN,{cross_subdomain_cookie:false});`

Or, use a CNAME to change from yourdomain.herokuapp.com to yourdomain.com.

See here: [Track Across Hosted Subdomains](https://help.mixpanel.com/hc/en-us/articles/115004507486-Track-Across-Hosted-Subdomains)

**Comment by tdumitrescu** [comment]
For what it's worth, I get the MP cookie just fine on that site, along with a bunch of others that are not in @cqcn1991's screenshot:

![screenshot from 2018-05-07 09-25-52](https://user-images.githubusercontent.com/855881/39712656-abe78f46-51d8-11e8-918a-dd2b6372b3d4.png)

**Comment by cqcn1991** [comment]
@jaredmixpanel Thanks! That's the right anwser. I just found the option at Segment, and when I turn it off, the cookie appears.
