### ISSUE TITLE
Option to disregard DNT flag

### ISSUE THREAD

**Issue by austince** [mixpanel/mixpanel-js#179]
Our company operates outside of the GDPR legislation and needs to track users in order to report back to their firms. Would you accept a PR that allowed for disregarding the DoNotTrack flag? Thank you!

**Comment by chrischen** [comment]
I was wondering why mixpanel-js was not working while the HTML snippet was. It turns out mixpanel-js respects Safari's Do Not Track setting while the HTML snipped doesn't!

**Comment by chrischen** [comment]
Calling mixpanel.opt_in_tracking() doesn't seem to work either.

**Comment by IsaiahJTurner** [comment]
Can we get a response from an admin? We're considering forking the repo but would rather this be supported.

**Comment by austince** [comment]
We're also using an internal fork @IsaiahJTurner for a couple of situations like this.

**Comment by sptutusukanta** [comment]
May be late here, I was too searching for a solution.
With latest mixpanel, there is a config option `ignore_dnt`, set it to `false` and start tracking users even with DNT enabled.

```
mixpanel.init('token', {
    ignore_dnt: true,
});
```

**Comment by tdumitrescu** [comment]
Sorry about the late reply here. Yes, this has been available since [v2.34.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.34.0). Closing out this issue, feel free to reopen if needed, thanks.
