### ISSUE TITLE
Offline event queue

### ISSUE THREAD

**Issue by nournia** [mixpanel/mixpanel-js#18]
Android version of Mixpanel library supports event queuing that makes it possible for offline apps to track user events. Is this feature on the roadmap of JavaScript lib?

**Comment by joeatwork** [comment]
Hi, @nournia!

It's unlikely we'll put queuing directly in the client side javascript library - often the JS client library is run only for very short periods, and it's usually run while the user is connected to a network, so we feel like offline features might not be appropriate for embedding into the library itself.

That said, you can implement your own queuing on top of the library if you need to- you'll need to do some timestamp management when you call track, but other than that it should be pretty straightforward.

Thanks!

**Comment by KeKs0r** [comment]
@nournia I am facing the same issue, did you come up with a event queuing solution?

**Comment by nournia** [comment]
No, I didn't. But I think @sandorfr is trying to solve #24 with such solution.

**Comment by olso** [comment]
Is offline queue being worked on?

**Comment by tdumitrescu** [comment]
It's not currently a prioritized project internally at Mixpanel - which means that the best way to move it ahead would be through a pull request.
