### ISSUE TITLE
Mixpanel events not sent

### ISSUE THREAD

**Issue by tavurth** [mixpanel/mixpanel-js#180]
#### Description :octocat:
Mixpanel events fail with `Mixpanel error: Bad HTTP status: 0`, or do not get sent at all.

#### Reproduction guide :beetle:

[Minimal repository](https://github.com/WASD-Team/mixpanel-issues)

`git clone git@github.com:WASD-Team/mixpanel-issues.git`
`cd mixpanel-issues`
Add your mixpanel api id in `./src/config.js`
`yarn`
`yarn start`

*Observed behaviour:* :broken_heart:
On our production site there are no mixpanel events being sent to the server.

When mixpanel is initialized the following result is given:
`{"notifications":[],"config":{"enable_collect_everything":false}}`

Sometimes mixpanel fails with HTTP Bad Status 

*Expected behaviour:* :heart:
- Mixpanel events are sent to the server and appear on the admin page
- `An event` is emitted to mixpanel

#### System Info :computer:
- OS: linux/OSX
- Browser: Firefox & Chrome
- Mixpanel version `2.22.4`

#### Backtrace :paw_prints:
```
Object { mixpanel: {…} } 
MIXPANEL REQUEST: 
Object { event: "mp_page_view", properties: {…} } 
MIXPANEL REQUEST: 
Object { event: "An event", properties: {…} } 
DEBUG: Object { event: "An event", properties: {…} } 
Mixpanel error: Bad HTTP status: 0
```

**Comment by jaredmixpanel** [comment]
@tavurth The mp_page_view Event is a vestigial event that the Mixpanel JavaScript library used to send by default to capture all page views. That event is automatically ignored by Mixpanel now, your own events that you are tracking with the mixpanel.track method should be okay. See: [History of "mp_page_view" Event](https://help.mixpanel.com/hc/en-us/articles/115004568086-History-Of-mp-page-view-Event)

**Comment by ljesus** [comment]
I'm also having this issue with my own custom events. Any clue?

**Comment by tdumitrescu** [comment]
For help with general integration issues, you'll get good, quick, personalized support by writing in to support@mixpanel.com. If you think your issue is related to a library bug, please open a new issue with as much detail as you can. Thanks!

**Comment by kembly** [comment]
FYI for people checking this problem out later. It looks like the issue is with 'Do Not Track' in chrome, as it works in firefox. You can check out: https://community.mixpanel.com/questions/539/integration-issue.html
