### ISSUE TITLE
mixpanel.track is mutating eventProperties object

### ISSUE THREAD

**Issue by cangoektas** [mixpanel/mixpanel-js#183]
Hi there,

I'm not sure why but calls to `mixpanel.track` mutate the `eventProperties` object. Example:

```js
mixpanel.identify('abc');

const myEvent = { foo: 'bar' };

mixpanel.track('Something happened', myEvent);

console.log(myEvent); // { foo: 'bar', token: 'myMixpanelToken' };
```

Unfortunately, this side-effect introduced a bug for us because we are using the `myEvent` object to make an API request which the server rejected because of the `token` property. I made the wrong assumption that `eventProps` wouldn't be mutated by a call to `track`.

Generally, I'd say that mutating user input is not a good practice. Can we change this behaviour and  make a copy of the `eventProperties` object?

**Comment by tdumitrescu** [comment]
This should be fixed as of https://github.com/mixpanel/mixpanel-js/releases/tag/v2.48.0
