### ISSUE TITLE
Nuxt vue

### ISSUE THREAD

**Issue by ThomasKientz** [mixpanel/mixpanel-js#187]
I am trying to use Mixpanel with [Nuxt](https://nuxtjs.org/) with no success.

I have created a plugin in `/plugins`

```
import mixpanel from "mixpanel-browser";

mixpanel.init("TOKEN", {
  debug: true,
  loaded: function() {
    mixpanel.track("loaded() callback works but is unnecessary"); //not received
    console.log("Mixpanel loaded successfully via Webpack/UMD");  //well printed in browser logs
  }
});

export default mixpanel;
```

Added it to `nuxt.config.js`

```
plugins: [
    { src: "@/plugins/mixpanel", ssr: false }
],
```

And use it in my components :

```
import mixpanel  from "@/plugins/mixpanel";

[...]
methods: {
  play() {
    mixpanel.track("play"); //not received
    console.log("mixpanel ", mixpanel); //output : "MixpanelLib {init: ƒ, _: {…}, __loaded: true, config: {…}, _jsc: ƒ, …}"
  }
} 
```

No error, but no events received in my dashboard and no traffic to mixpanel recorded.

**Comment by tdumitrescu** [comment]
The lib initialization seems fine. If you write in to support@mixpanel.com we can take a look at your specific setup and help troubleshoot.

Note that the mixpanel-browser package can be bundled/imported via frontend bundlers like webpack, but will only send actual network calls when running in a browser, so your ssr setup won't be tracking while rendering.

**Comment by ThomasKientz** [comment]
@tdumitrescu Thanks, I am writing to support.

Sure thing for the SSR, I am sending events when running in the browser trough a button that fire a method.

**Comment by ThomasKientz** [comment]
@royandre not a relevant one. I ended up using the html script tag rather than the npm lib !

**Comment by SarasArya** [comment]
Hi, I am facing the same issue. Everything loads successfully but no events are being triggered.

**Comment by juanjcardona13** [comment]
> [@royandre](https://github.com/royandre) not a relevant one. I ended up using the html script tag rather than the npm lib !

Could you share with me how you did it with just the tag, please?

**Comment by juanjcardona13** [comment]
> Hi, I am facing the same issue. Everything loads successfully but no events are being triggered. This was not working in Chrome but working in Safari. So I dug up a little and found this do not track option that I enabled in Chrome. For sites like Mixpanel to work you need to disable that option. To do this, you need to go to Chrome settings and search for Do not track and disable it. Hope this helps. Found the solution from [here](https://community.mixpanel.com/questions/539/integration-issue.html)

Will this also happen to end users?
