### ISSUE TITLE
Compress mixpanel js

### ISSUE THREAD

**Issue by daviddening** [mixpanel/mixpanel-js#190]
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fmarketplace-fe-prod.us-east-1.elasticbeanstalk.com%2Fmarketplace%2Fwedding-reception-venues-new-york-ny&tab=desktop

<img width="864" alt="screen shot 2018-09-27 at 3 08 17 pm" src="https://user-images.githubusercontent.com/1488756/46168829-8abf1a00-c267-11e8-8973-ccf99f99d2e8.png">

This is still happening today.

**Comment by tdumitrescu** [comment]
That looks like the Segment SDK???

**Comment by daviddening** [comment]
@tdumitrescu  It sure is, but Segment is just taking caching mixpanel's (presumably uncompressed) js.  I also cross posted this on Segment's site.  It seems like every month or two this issue comes back and tanks performance for a couple weeks.

**Comment by tdumitrescu** [comment]
No, Segment's analytics.min.js shown in the screenshot above is a different SDK. The Mixpanel SDK that you're loading comes directly from our CDN with filename mixpanel-2-latest.min.js. On the site that you linked, it is served compressed:
![screen shot 2018-09-28 at 9 54 39 am](https://user-images.githubusercontent.com/855881/46222351-d7a4fe00-c304-11e8-8204-6842ec622ec1.png)

**Comment by daviddening** [comment]
@tdumitrescu  Apologies, I saw the error pop up and assumed it was a recurrence of 
https://github.com/mixpanel/mixpanel-js/issues/168

I'll bother the correct folks

**Comment by tdumitrescu** [comment]
No worries! If you have mixpanel-js config/serving issues and want to go over particulars of your setup in private, emailing support@mixpanel.com is also a good way to go.
