### ISSUE TITLE
Track two durations with the same event name

### ISSUE THREAD

**Issue by Lebron1992** [mixpanel/mixpanel-js#192]
Hello!

Can we track two durations with the same event name? Please look at the following example:

Assume we have a event name of "ON_MATCHUP_TAB" and a property of "isBoxScoreVisible". I want to track the two durations: 1) duration of "ON_MATCHUP_TAB"; 2) duration of "ON_MATCHUP_TAB" with "isBoxScoreVisible" set to "false". 

Could we write the code like this:

```
// time event
mixpanel.time_event("ON_MATCHUP_TAB");
mixpanel.time_event("ON_MATCHUP_TAB", { "isBoxScoreVisible": false });

// track event
mixpanel.track("ON_MATCHUP_TAB");
mixpanel.track("ON_MATCHUP_TAB", { "isBoxScoreVisible": false });
```

and distinguish the two duration with property of "isBoxScoreVisible"?

Thanks!

**Comment by tdumitrescu** [comment]
At the moment, `time_event` [only supports `event_name` as a timer key](https://github.com/mixpanel/mixpanel-js/blob/4a107013408bc743dbc23aeb9ecbe79c5054ee52/src/mixpanel-core.js#L674). We'd be happy to look at a PR adding prop support for your use case.

**Comment by Lebron1992** [comment]
@tdumitrescu  OK! Thanks for your answer.
