### ISSUE TITLE
add support for AMD (specifically require.js) loading

### ISSUE THREAD

**Issue by dorongutman** [mixpanel/mixpanel-js#2]

**Comment by tom-coefficient** [comment]
+`

**Comment by unthunk** [comment]
+1.  The workarounds are handy until you need to use the requirejs optimizer, then it just falls apart.

**Comment by gsastry** [comment]
Any updates on this a few months later?

**Comment by tdumitrescu** [comment]
planning on getting this in before the end of april. sorry this is taking a while. will post back here when there's news.

**Comment by bmcorser** [comment]
@tdumitrescu April has been and gone, any news here?

**Comment by tdumitrescu** [comment]
Sorry, got a little overambitious wrt scheduling and mixpanel product priorities. There's a prototype but it's not ready for release; unfortunately can't give an ETA at the moment, but please trust that this isn't forgotten.

**Comment by KeKs0r** [comment]
+1 I am really looking forward to an CommonJS version on NPM!

**Comment by tdumitrescu** [comment]
We now have a PR open with the necessary basic changes: https://github.com/mixpanel/mixpanel-js/issues/37 so it won't be too much longer. Thanks again for your patience.

**Comment by Josh-a-e** [comment]
+1 - any progress on this?

**Comment by AdnanTheExcellent** [comment]
+1

**Comment by tdumitrescu** [comment]
AMD/CJS/UMD/ES2015 module support is available as of v2.7.0 (https://github.com/mixpanel/mixpanel-js/releases/tag/v2.7.0). See https://github.com/mixpanel/mixpanel-js/tree/master/examples for some usage examples; documentation in README coming soon.
