### ISSUE TITLE
Ctrl+click doesn't work with mixpanel.track_links

### ISSUE THREAD

**Issue by pfhayes** [mixpanel/mixpanel-js#20]
I've enabled mixpanel.track_links on some links on my site - however, when a user uses Ctrl+click to click on these links, they expect the link to open in a new tab - however, the link opens on the same page.

track_links works as expected when the user middle clicks, or uses command-click on OS X.

**Comment by tdumitrescu** [comment]
Hi, thanks for the note. Can you provide some info on the OS and browser involved? Much appreciated!

**Comment by pfhayes** [comment]
This has been observed in chrome on Ubuntu and windows.

**Comment by pfhayes** [comment]
The relevant line appears to be https://github.com/mixpanel/mixpanel-js/blob/b90d7d428b568c11a4ceccd618d0d217d130894c/mixpanel.js#L1509

The code detects `metaKey`, which is what is used on OS X to open links in a new tab. However, on Windows / Ubuntu, `ctrlKey` is the appropriate check, because on those platforms Ctrl-click opens links in a new tab, and meta-click does not.

**Comment by tdumitrescu** [comment]
Thanks for looking that up, we'll patch soon!

**Comment by tdumitrescu** [comment]
Patched in v2.3.4, thanks for the heads up!

**Comment by pfhayes** [comment]
thanks!
