### ISSUE TITLE
missing var declaration on mixpanel-jslib-snippet.js

### ISSUE THREAD

**Issue by agustinhaller** [mixpanel/mixpanel-js#215]
Hi, this is a simple one to fix.
I noticed there are a couple `var` declarations missing in the `mixpanel-jslib-snippet.js` file.

https://github.com/mixpanel/mixpanel-js/blob/a83b082679946df988f9964a32336dd7d8141181/mixpanel-jslib-snippet.js#L90-L91

As I'm using the snippet source code to load mixpanel lib from my Typescript code asynchronously. The Typescript compiler is complaining about those missing `var` declarations.

If you wonder why I'm using the snippet code directly in my Typescript files, it's because I don't want to include the snippet in my index.html as I want to keep scripts in the index.html file to a minimum to avoid blocking the UI thread.
I think this approach is a nice workaround for [this issue](https://github.com/mixpanel/mixpanel-js/issues/128).

**Comment by tdumitrescu** [comment]
Thanks for the catch! We'll get it in an upcoming release, though you can always expedite by submitting a PR.

Re: bundling the async loader ("snippet"): that's a workable approach as long as you ensure you always run that JS bundle before you ever try to access `window.mixpanel`. The minified snippet _is_ designed to be small enough to put in a page's `<head>` tag without any noticeable delay, and then you don't have to worry about loading order at all. The issue being discussed in https://github.com/mixpanel/mixpanel-js/issues/128 is different: the problem there is the size of the actual library code, which will only affect you when you try to put the entire lib in your bundles (i.e. bypassing the async loader altogether).

**Comment by tdumitrescu** [comment]
Sorry this slipped under the radar; it's been fixed in [v2.45.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.45.0).
