### ISSUE TITLE
Publish 2.28.0 on npm

### ISSUE THREAD

**Issue by rodrigoalmeidaee** [mixpanel/mixpanel-js#216]
Hi there,

Is there any reason why mixpanel-browser published on npm is still at 2.27.1? (https://www.npmjs.com/package/mixpanel-browser)

We want to use a feature that was only made available on 2.28.0, and while our tooling can install from a git source directly things work a bit better if we could simply pin the package version and let it be installed from npm.

Thanks!

Rodrigo.

**Comment by tdumitrescu** [comment]
Hi @rodrigoalmeidaee, sorry about that! 2.28.0 is now available on npm.

**Comment by rodrigoalmeidaee** [comment]
Wow @tdumitrescu that was fast! Thanks for the quick publish 👍
