### ISSUE TITLE
Calling .identify() doesn't work

### ISSUE THREAD

**Issue by edhenderson** [mixpanel/mixpanel-js#219]
My code for example

```
this.mixpanel.identify(id);
```

My code works fine for tracking events, all good. I call `identify` with `id`, e.g. `12345-6789` (its a mashup of the org id and the user id).

Is this a known issue, am I doing something wrong?

**Comment by cassiegamm** [comment]
Hi @edhenderson,

Could you clarify what you're expecting to happen when you call identify, vs what you are observing?

**Comment by edhenderson** [comment]
![Screenshot 2019-08-21 at 09 41 41](https://user-images.githubusercontent.com/1378582/63416770-f9fda980-c3f7-11e9-9866-427a4a3d1317.png)

When I go into the control panel for Users, I get this. Even though in my code I am using identify.

**Comment by cassiegamm** [comment]
Ah, I see.

In order to get data in your project, you'll want to utilize the mixpanel.track method: 
https://developer.mixpanel.com/docs/javascript#section-sending-events

**Comment by edhenderson** [comment]
Yes, done that, can see events firing fine.

**Comment by edhenderson** [comment]
I can see the distinct ID in the data

![Screenshot 2019-08-21 at 10 22 00](https://user-images.githubusercontent.com/1378582/63419917-91193000-c3fd-11e9-96d1-89513c206218.png)

But clicking the ID takes me to the page to setup Users:

![Screenshot 2019-08-21 at 10 23 08](https://user-images.githubusercontent.com/1378582/63419985-b0b05880-c3fd-11e9-91fe-ff4488fbe505.png)

**Comment by cassiegamm** [comment]
Got it. Thanks for the images. 

In order to create user profiles, you'll want to utilize a method such as people.set(): 
https://developer.mixpanel.com/docs/javascript#section-storing-user-profiles
