### ISSUE TITLE
Cookie name is not valid

### ISSUE THREAD

**Issue by thanatos** [mixpanel/mixpanel-js#23]
We're seeing cookie names such as `mp_:192.0.<snip>_mixpanel`. The [`:` is not a valid character in a Cookie name](http://tools.ietf.org/html/rfc6265#page-9), and while Chrome and nginx both forward this alright, our backend Python library (Tornado) chokes on it, and drops the entire `Cookie` header. (Which contains other cookies as well.)

Can this character be removed from whatever generates the name for the Mixpanel cookie?

(note: we're using version 2.2, I think, from the CDN)

**Comment by tdumitrescu** [comment]
Anything between `mp_` and `_mixpanel` is provided by your own code; see https://github.com/mixpanel/mixpanel-js/blob/5c38703f88c42a95d820d366b76adf95563bdb21/mixpanel.js#L1562. The 'token' value in the config is what you provide to `mixpanel.init()` - maybe something fancy in your provisioning is injecting more than just the mixpanel token into the JS code?

**Comment by thanatos** [comment]
@tdumitrescu Ah, I think you're right! Thank you for pointing me down that path: I think I've tracked down where that gets set in our deployment stuff. Closing this.

**Comment by tdumitrescu** [comment]
No problem, glad to help!
