### ISSUE TITLE
Any work needs to be done for the new cross site cookie rules?

### ISSUE THREAD

**Issue by jonyeezs** [mixpanel/mixpanel-js#243]
Chrome and the rest of the browsers are being more strict with how cross-site cookies should operate.

https://web.dev/samesite-cookie-recipes/

Is there any consideration of having this implemented?

If the library is to be `cross_subdomain_cookie = true`, it should add cookie attributes `SameSite=None; Secure`. And the `secure_cookie` option should be removed as that's going to be managed by what kind of cookie it is.

**Comment by tdumitrescu** [comment]
Do you have a source for cross-subdomain cookies being treated as "cross-site" or "3rd-party"? According to the [SameSite draft spec](https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-2.1) it's considered same-site when the target's "registrable domain" matches the request's "site for cookies" - or in more legible terms from https://web.dev/samesite-cookies-explained/:

"The introduction of the SameSite attribute (defined in RFC6265bis) allows you to declare if your cookie should be restricted to a first-party or same-site context. It's helpful to understand exactly what 'site' means here. The site is the combination of the domain suffix and the part of the domain just before it. For example, the www.web.dev domain is part of the web.dev site.

Key Term:

If the user is on www.web.dev and requests an image from static.web.dev then that is a same-site request.

The public suffix list defines this, so it's not just top-level domains like .com but also includes services like github.io. That enables your-project.github.io and my-project.github.io to count as separate sites."

**Comment by robcrocombe** [comment]
I've been seeing this warning in the dev console for quite a while now:

>A cookie associated with a cross-site resource at http://mixpanel.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

I think you just need to set that `SameSite` attribute in the library?

**Comment by tdumitrescu** [comment]
@robcrocombe see https://github.com/mixpanel/mixpanel-js/issues/224 for that one

**Comment by aakarim** [comment]
This seems to affect my chrome extensions, the url it sends from isn’t my website domain but chrome://extensions:ID. An option to enable Samesite:None would be nice.

**Comment by CraigMcCahill** [comment]
We at provenance.org use mixpanel in an iframe as an embed for third-party customers so we definitely need you to set `samesite=None` and `secure=true`.

**Comment by tdumitrescu** [comment]
Interesting use cases. Would a config option to turn on SameSite=None (and secure) be sufficient?

**Comment by CraigMcCahill** [comment]
> Interesting use cases. Would a config option to turn on SameSite=None (and secure) be sufficient?

Yes, thank you my understanding is that is all we need.

**Comment by tdumitrescu** [comment]
The new config option has been released in https://github.com/mixpanel/mixpanel-js/releases/tag/v2.35.0. Use it like so:
```js
mixpanel.init('my token', {cross_site_cookie: true});
```
Thanks!
