### ISSUE TITLE
/decide returns 405 when using api_transport: 'sendBeacon'

### ISSUE THREAD

**Issue by ahem** [mixpanel/mixpanel-js#244]
If I initalize the mixpanel library this way then I see failing (405) requests to `https://api-js.mixpanel.com/decide`:
```
mixpanel.init(mixpanelId, {
    api_transport: 'sendBeacon'
});
```

It looks to me like this is caused by init calling the decide endpoint with 'sendBeacon' instead of plain XHR. At least I can work around the problem this way:

```
mixpanel.init(mixpanelId, {
    loaded: () => {
        mixpanel.set_config({ api_transport: 'sendBeacon' });
    }
});
```
When using the above workaround I see valid GET requests with 200 responses to /decide and still get the sendBeacon (json / POST) requests for tracking events.

Maybe the solution is as simple as setting a proper `api_transport` here: https://github.com/mixpanel/mixpanel-js/blob/f0fed1b541acc9d6cd2fac2234a9b5da3646dd21/src/autotrack.js#L236

**Comment by tdumitrescu** [comment]
Thanks for the report. Yeah, this looks like an issue with needing to ignore `sendBeacon` when a GET request is specified. We'll get a fix out shortly.
