### ISSUE TITLE
Why does mixpanel generates new distinct_id after calling mixpanel.track(event)?

### ISSUE THREAD

**Issue by zhdanouskikh** [mixpanel/mixpanel-js#245]

**Comment by tdumitrescu** [comment]
This sounds like probably an issue with the specifics of your implementation; it's not the normal behavior of the library. You can submit a request with our smart and friendly support staff at https://mixpanel.com/get-support.

If you get more information and have good reason to suspect a bug in the library, please feel free to reopen, thanks.

**Comment by zhdanouskikh** [comment]
@tdumitrescu thanks, will try luck with support :)
