### ISSUE TITLE
Does not fire tracking callback when using api_transport: 'sendBeacon'

### ISSUE THREAD

**Issue by ahem** [mixpanel/mixpanel-js#250]
When using `api_transport: 'sendBeacon' the tracking callback isn't called. If that is by design, then I think it should be explicitly mentioned in the documentation, since that is definitely not what I expect.

I think that it should be very easy to fix this, basically just call the callback from the block in the if statement here:
https://github.com/mixpanel/mixpanel-js/blob/master/src/mixpanel-core.js#L397-L402

Since the sendBeacon api doesn't really have a response object, then maybe it should mock one, similar to how the error branch of the XHR transport branch does it (https://github.com/mixpanel/mixpanel-js/blob/master/src/mixpanel-core.js#L441). So maybe, something like this:
```
        try {
            if (sendBeacon(url, body_data)) {
                callback({ status: 200 });
            } else {
                callback({ status: 0, error: 'sendBeacon failed to track' });
            }
        } catch (e) {
            console.error(e);
            callback({ status: 0, error: `error calling sendBeacon: ${e}` });
        }
```

**Comment by tdumitrescu** [comment]
Sorry, I thought we'd covered this in the docs but in retrospect this could be talking about the web api too: "[the sendBeacon API does not support callbacks or any way to know the result of the request](https://developer.mixpanel.com/docs/javascript-full-api-reference#section-mixpanel-set-config)."

In principle the tracking callback is supposed to report whether the event was successfully queued up by Mixpanel's API servers, not the fact that a request was made (for which you don't need a callback at all; you'll know from the return value of `mixpanel.track()` whether the network call was attempted or not). You're right though that we currently don't take the return value of `navigator.sendBeacon()` into account. Would you be ok with `mixpanel.track()` returning a falsey value when sendBeacon does? This would be in line with the existing convention, where track() doesn't call the callback if it never makes the request.

**Comment by ahem** [comment]
Sure, this would be a good solution. Although, maybe it should be documented that the `mixpanel.track()` function has a return value and that it can be used like this?

The current documentation doesn't seem to mention that at all: https://developer.mixpanel.com/docs/javascript-full-api-reference#section-mixpanel-track

**Comment by tdumitrescu** [comment]
OK, as of https://github.com/mixpanel/mixpanel-js/releases/tag/v2.35.0 the `track()` method should be returning `false` when the return value of `sendBeacon` is falsey (i.e. the request wasn't successfully enqueued).

The documentation has also been updated to include the return value: https://developer.mixpanel.com/docs/javascript-full-api-reference#section-mixpanel-track

Thanks for the report!
