### ISSUE TITLE
Import old event returns {"error": null, "status": 1}

### ISSUE THREAD

**Issue by crosety** [mixpanel/mixpanel-js#255]
Hi, I am trying to use the import old events endpoints as mentioned in the documentation here: [https://developer.mixpanel.com/docs/importing-old-events](https://developer.mixpanel.com/docs/importing-old-events) 

I have followed all the steps but I always seem to get the following response: 
{
	"error": null,
	"status": 1
}

I have been spending a lot of time playing with this to realise it has something to do with the API Secret. If I write another value, I get the same error but if I just don't pass an auth value, I get a different error so I'm guessing it means that I don't have permission to call this API? I am sure that I am sending the right API secret and I don't really know what to do at this point.

My request looks like this:

POST /import HTTP/1.1
Host: api.mixpanel.com
User-Agent: Charles/4.5.5
Authorization: Basic <Base64 encoded '<Api Secret>:'>
Content-Length: 207
Content-Type: application/x-www-form-urlencoded

data=<Base64 encoded event data>&verbose=1

Thanks in advance!

**Comment by tdumitrescu** [comment]
Hi, unfortunately this doesn't appear to be an issue with this SDK, as it doesn't support the /import endpoint (which you should never do from client-side code, as it requires non-public credentials).

A good place to ask general integration questions like this is Mixpanel's community support site QBQ. Here's the topic ["Sending Data to Mixpanel"](https://community.mixpanel.com/sending-data-to-mixpanel-11).
