### ISSUE TITLE
cookies are being blocked in Chrome 84

### ISSUE THREAD

**Issue by aforty** [mixpanel/mixpanel-js#261]
I looked at the documentation but I'm not sure how to resolve this. All tracking has stopped. When I go into Application>Storage>Cookies I don't see any from mixpanel. I've tried passing `{ cross_site_cookie: true }` into init.

![Screen Shot 2020-07-29 at 11 11 24](https://user-images.githubusercontent.com/523683/88818136-59c60e00-d18c-11ea-8fc6-82baf3c7cc00.png)

![Screen Shot 2020-07-29 at 11 11 39](https://user-images.githubusercontent.com/523683/88818076-47e46b00-d18c-11ea-94fe-47b1e108f34e.png)

**Comment by tdumitrescu** [comment]
Take a look at https://github.com/mixpanel/mixpanel-js/issues/224 - this looks like the same issue, i.e., the warnings you're seeing are about your personal cookies from the mixpanel.com website not getting sent with requests to api-js.mixpanel.com, which is totally fine and won't affect your project, and won't appear for your users. This is supported by your screenshot above, which only contains cookies from the Mixpanel UI/site.

The superproperty cookies used by this SDK are _not_ set on mixpanel.com, they are set on the domain your site runs under, so they are 1st-party cookies and aren't affected by SameSite restrictions. The only way this doesn't hold is if you explicitly set a different cookie domain in your config. And even if cookies are somehow blocked, tracking calls should still be going out, it would only affect the persistence of superproperties across page loads.

**Comment by aforty** [comment]
Well persistent super properties are definitely something I'm trying to use.

I guess I don't know all that much about how mixpanel actually works but the fact that the script is trying to set cookies and they aren't sticking because of brand new browser restrictions seems like a problem.

**Comment by tdumitrescu** [comment]
> These issues are only being reported because I visited and logged into mixpanel.com which has set cookies and this isn't something that should affect other users.

That's right. You should be able to verify by checking in an incognito window (where you aren't logged into mixpanel.com).

**Comment by SaelbenNoa** [comment]
I am having the same issue, however, my along with the cookies blocked, it also shows a request in the blocked list.

We are running the latest version of mixpanel and are testing it locally on our app. I set it up according to instructions, and tried several different ways, including the react-mixpanel package, a raw wrapper for mixpanel-browser and most recently the react-mixpanel-provider-component package. I also tried this tutorial.

We are running on Chrome, and after installing the mixpanel debugger, I found

Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute

Which is affecting 2 cookies and 1 request.

The request heads to https://api-js.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=TOKEN&ip=1&_=SOMENUMBER and according to chrome network tab returns 200.

Mixpanel.com shows no data, and the check on the setup page says no data is coming.

The implementation was also tested in incognito mode. It is simply calling it during an onClick event in a component.

**Comment by tdumitrescu** [comment]
@SaelbenNoa I don't think this is a symptom of what's being discussed in this issue. And if your cookies do get blocked for some reason, that does not stop events from showing up. It sounds like you have some issue getting your integration set up in the first place. I'd recommend checking in the help topics and community forums at https://community.mixpanel.com/.
