### ISSUE TITLE
Batch Requests fails when api_host is set

### ISSUE THREAD

**Issue by chriszamierowski** [mixpanel/mixpanel-js#265]
[v2.37.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.37.0) began opting consumers into Batch Requests if `batch_requests` isn't passed as a configuration option. However, if `api_host` is set to be something other than Mixpanel's API, there is no guarantee that it supports Batch Requests. By rolling consumers onto Batch Requests it is possible to silently break functionality with just a minor version bump of this package, which is difficult to debug.

**Comment by tdumitrescu** [comment]
Fixed in [v2.39.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.39.0)
