### ISSUE TITLE
No Data on setup check, implemented in React.js

### ISSUE THREAD

**Issue by SaelbenNoa** [mixpanel/mixpanel-js#267]
We are running the latest version of mixpanel and are testing it locally on our app. I set it up according to instructions, and tried several different ways, including the react-mixpanel package, a raw wrapper for mixpanel-browser and most recently the react-mixpanel-provider-component package. I also tried this [tutorial](https://medium.com/@andrewoons/setting-up-mixpanel-in-react-3e4c5b8c2a36).

We are running on Chrome, and after installing the mixpanel debugger, I found 

> Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute

Which is affecting 2 cookies and 1 request. 

The request heads to https://api-js.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=TOKEN&ip=1&_=SOMENUMBER and according to chrome network tab returns 200.

Mixpanel.com shows no data, and the check on the setup page says no data is coming.

The implementation was also tested in incognito mode. It is simply calling it during an onClick event in a component.

**Comment by tdumitrescu** [comment]
duplicated at https://github.com/mixpanel/mixpanel-js/issues/261#issuecomment-676723617
