### ISSUE TITLE
Mixpanel cookies are blocked by browser cause of the SameSite issue

### ISSUE THREAD

**Issue by lancee** [mixpanel/mixpanel-js#269]
Hi team

I need help of a SameSite cookie issue, thank you in advance.

I got the following issue cause of SameSite/cross-site-cookie, since I installed the version `2.39.0`.

And I have this setup in my JS `mixpanel.init("my token", { cross_site_cookie: true, persistence: "localStorage" });`

Anything I can do to avoid this?

Thanks.

```console
A cookie associated with a cross-site resource at http://mixpanel.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

<img width="1290" alt="DevTools" src="https://user-images.githubusercontent.com/385489/92985384-ddde1600-f4ec-11ea-8ef0-25a37b28c4b9.png">

**Comment by tdumitrescu** [comment]
Take a look at https://github.com/mixpanel/mixpanel-js/issues/224 - this looks like the same issue, i.e., the warnings you're seeing are about your personal cookies from the mixpanel.com website not getting sent with requests to api-js.mixpanel.com, which is totally fine and won't affect your project, and won't appear for your users.

The superproperty cookies used by this SDK are not set on mixpanel.com, they are set on the domain your site runs under, so they are 1st-party cookies and aren't affected by SameSite restrictions. The only way this doesn't hold is if you explicitly set a different cookie domain in your config. And even if cookies are somehow blocked, tracking calls should still be going out, it would only affect the persistence of superproperties across page loads.

**Comment by lancee** [comment]
@tdumitrescu Understood, thank you for your help and the detailed answer.
