### ISSUE TITLE
Error Expected ';'

### ISSUE THREAD

**Issue by saadaouad** [mixpanel/mixpanel-js#271]
First of all I'd like to thank you for this package,

I'm getting this error raised on Sentry: 

**Error Expected ';'**

<img width="835" alt="Screen Shot 2020-11-10 at 5 29 13 PM" src="https://user-images.githubusercontent.com/17694380/98702110-4ffe9a00-237a-11eb-91f3-e005d2dc99f4.png">

It would be great to add a semicolon before `nthChild` var

**Comment by tdumitrescu** [comment]
That is very odd. First off here's the fuller context of what comes before your L2172:
```js
        if (shouldTrackElement(elem)) {
            _.each(elem.attributes, function(attr) {
                if (shouldTrackValue(attr.value)) {
                    props['attr__' + attr.name] = attr.value;
                }
            });
        }

        var nthChild = 1;
        var nthOfType = 1;
        var currentElem = elem;
```
There's certainly no semicolon required after the `if {}` block, and the library's Closure Compiler settings will fail to build any non-ES5-compatible syntax.

It also looks like in your image, it's indicating the _end_ of that line (char 20 of line 2172).

It might be useful to have more context from your Sentry report, for instance did this happen on a particular browser+version?

**Comment by saadaouad** [comment]
> There's certainly no semicolon required after the if {} block

Yes `if {}` statement it doesn't require a semicolon at the end.

> It might be useful to have more context from your Sentry report

I can't provide you with more extra data since this is all what we have tracked in this event

> for instance did this happen on a particular browser+version?

Yes it happens only on a particular browser:

**Browser**
- name:  Edge
- version: 12.10240


BTW this event/error is raised only from **one user**, I think it doesn't matter to dig into that ATM since there is no clear context to debug this. I'll keep you updated if this happens again.

Thanks,
