### ISSUE TITLE
Setting cookie only on a subdomain

### ISSUE THREAD

**Issue by gaurav5430** [mixpanel/mixpanel-js#303]
We have a Saas product which we host on our partners domain (partner.com), as a subdomain (ourproduct.partner.com). The analytics / tracking for our product belongs to us and we use mixpanel along with other analytics libraries. The partner may have their own mixpanel setup on the top level domain. It seems that our mixpanel instance is setting the cookie on .partner.com instead of ourproduct.partner.com. this means that our cookie is visible to the partner top level domain, and would also interfere with their mixpanel

is there a way to set the cookie only on the specific subdomain that our app runs on?

**Comment by tdumitrescu** [comment]
Thee `cross_subdomain_cookie` config option should take care of this:
```js
mixpanel.init(`<TOKEN>`, {cross_subdomain_cookie: false});
```
Alternately, using `{persistence: 'localStorage'}` will keep things scoped to your subdomain (and avoid sending superproperty cookies over the wire).

**Comment by gaurav5430** [comment]
it seems like the `cross_subdomain_cookie: false` works, I am still not clear on why it works though ?

This is what I got from support:

>Thank you for contacting Mixpanel support. The default cross_subdomain_cookie config is set to true in your mixpanel.init function, which will allow your subdomain's cookie to be stored and keep the Mixpanel distinct ID and super properties consistent across the sub-domain: mixpanel.init(PROJECT_TOKEN,{cross_subdomain_cookie:true});
Or, use a CNAME to change from yourdomain.partner.com to yourdomain.com.

**Comment by tdumitrescu** [comment]
> it seems like the cross_subdomain_cookie: false works, I am still not clear on why it works though ?

When `cross_subdomain_cookie` is false, the cookie-setting code will not include a `domain=` attribute in the cookie. When no domain is specified, the cookie is by default scoped to the current host; see https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent.

**Comment by gaurav5430** [comment]
Thanks, this works, and now I understand the reason why.
