### ISSUE TITLE
allow /track endpoint to be renamed/localized in proxy deployments

### ISSUE THREAD

**Issue by ak--47** [mixpanel/mixpanel-js#306]
when [self-hosting mixpanel and deploying from a proxy](https://developer.mixpanel.com/docs/self-hosted-tracking) the SDK provides config options for changing the API host, so that they can match the proxy:

```
mixpanel.init("<YOUR_PROJECT_TOKEN>", {api_host: "https://<YOUR_PROXY_DOMAIN>"});
```

The nginx deployment we recommend also makes it possible to change the routes this proxy accepts:
https://github.com/mixpanel/tracking-proxy/blob/master/nginx.conf

something like:
```
location /recordUserAction {
    proxy_set_header Host api.mixpanel.com;
    proxy_set_header X-Real-IP $http_x_forwarded_for;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_pass https://api.mixpanel.com/track;
}
```

this implementation is highly useful as _some_ ad-blockers (like [easyprivacy](https://github.com/easylist/easylist/search?q=%2Ftrack)) will block all requests to `*/track` regardless of the domain they are issued to.

currently, to get the above-mentioned implementation to work properly (where the SDK makes requests to `/recordUserAction` _instead_ of `/track`), you'd need to fork the SDK and change [this line](https://github.com/mixpanel/mixpanel-js/blob/8b2e1f7b/src/mixpanel-core.js#L1127):
```
 this.get_config('api_host') + '/track/',
```

to

```
 this.get_config('api_host') + '/recordUserAction/',
```

which introduces unnecessary complexity.

it would be ideal if the API routes were localizable, just like the `api_host` is; something like:
```
mixpanel.init("<YOUR_PROJECT_TOKEN>", {api_host: "https://<YOUR_PROXY_DOMAIN>", "track_route": "/recordUserAction/"})
```

i believe the only relevant api routes would be `/track`, `/engage/`, `/decide/`, `/groups`

**Comment by tdumitrescu** [comment]
Configurable API endpoints are now supported as of https://github.com/mixpanel/mixpanel-js/releases/tag/v2.48.0

**Comment by tdumitrescu** [comment]
@black-snow decide has been deprecated for years and this sdk no longer makes calls to it. So if you have an sdk version that supports renaming endpoints, then you don't have to worry about decide anymore.

**Comment by black-snow** [comment]
@tdumitrescu thanks for the quick reply! Would you mind giving [this](https://github.com/mixpanel/tracking-proxy) an update? It's just replacing decide with track, engage, and groups then, right? And with no need for `/`.
