### ISSUE TITLE
`PetalBot` should be a blocked user agent

### ISSUE THREAD

**Issue by jebax** [mixpanel/mixpanel-js#316]
Hi there,

At the moment, Huawei's `PetalBot` isn't included in your list of blocked user agents. We've blocked it manually in our code, but it'd be nicer if you guys blocked it in the mixpanel library.

Additionally, I noticed that your [list of blocked UA strings](https://github.com/mixpanel/mixpanel-js/blob/d192aefb6d549a267f8fa825bc2e13e5b2c4f9c4/src/utils.js#L944) isn't very long / exhaustive. Could it be better if you guys used a library like [isbot](https://www.npmjs.com/package/isbot) to determine which user agents to block instead? That way we'd be unlikely to have this issue in the future. Maybe I'm missing something though and there's a reason you're not using a third party library.

Thanks in advance!

**Comment by tdumitrescu** [comment]
Thanks @jebax. We'll get PetalBot blocked in the next patch release soon. One of the things blocking us from putting a big user agent list + library in this SDK is the size that it would add, which is already a touchy subject for users who don't load it asynchronously (and we're working on big size reductions for early 2022). Beyond that, we want to move the bot-detection/blocking mostly out of the client (SDK) and into the API server side of things, where it can be updated seamlessly without requiring new client versions to roll out to end users.

**Comment by tdumitrescu** [comment]
PetalBot should be blocked now as of v2.42.1, thanks for your patience.
