### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by contra** [mixpanel/mixpanel-js#32]
can you publish this on npm so it can be used with browserify?

**Comment by tdumitrescu** [comment]
We're planning on it, but first have to get the time to set up commonjs/amd support in the lib. Follow https://github.com/mixpanel/mixpanel-js/issues/2 for news on that front, thanks.

**Comment by contra** [comment]
@tdumitrescu #2 has been open for over a year, I don't understand why you also have to add amd support before you can run the command.

Multiple people have forked this repo and published it to npm already because they got sick of waiting but they never keep it up to date, so you've got people using old versions of mixpanel in the wild because of this

**Comment by tdumitrescu** [comment]
We still need to update the lib code to make it work out of the box with commonjs/browserify, that's why it's not done already. If you have particular thoughts it will be more useful to post them on #2, thanks.

**Comment by evanhammer** [comment]
Is there any update @tdumitrescu on publishing to NPM? It looks like #2 is closed and you support amd/commonjs. Thanks!

**Comment by tdumitrescu** [comment]
It was put on NPM quietly a while ago; just the installation documentation hasn't been updated yet: https://www.npmjs.com/package/mixpanel-browser (named `mixpanel-browser` since `mixpanel` has been taken for years by our node.js lib). Enjoy!

**Comment by evanhammer** [comment]
thanks!

**Comment by evanhammer** [comment]
@tdumitrescu I installed via npm but I can't find the module. Does the npm install provide access to the commonJS modules?

As in, can I do this?
```
var mp = require('mixpanel-browser')
```

Thanks.

**Comment by oncletom** [comment]
The `main` field of package.json seems to aim at the `dist/mixpanel.global.js`, which indeed does not export anything. Ideally the `main` field should aim at `dist/mixpanel.umd.js` to make the code requirable through CommonJS.

In the meantime, this should do the trick:

```js
var mp = require('mixpanel-browser/dist/dist/mixpanel.global');
```

**Comment by tdumitrescu** [comment]
@oncletom is correct that right now you need to require into the guts of the build dir. https://github.com/mixpanel/mixpanel-js/pull/61 will fix that so that you can just `require('mixpanel-browser')`. Will post back here when it's published.

**Comment by evanhammer** [comment]
Awesome. Thanks for breaking it down!

**Comment by tdumitrescu** [comment]
Alright @evanhammer v2.7.2 is available on NPM now and will let you require the CommonJS build with `require('mixpanel-browser')`. Thanks for the push so we could get this cleaned up!

**Comment by evanhammer** [comment]
Just installed it via NPM and tested CommonJS. Looking great. Thanks!

**Comment by mteodori** [comment]
how can I install a later version? npm does not seem to get updated at each release

**Comment by tdumitrescu** [comment]
The latest version on npm (https://www.npmjs.com/package/mixpanel-browser), 2.7.2, is up to date feature-wise. The only differences in 2.7.3-2.7.9 are for Mixpanel's internal statistics collection (see https://github.com/mixpanel/mixpanel-js/blob/master/CHANGELOG.md). Rest assured that new versions do get published on npm when they contain functional changes.

**Comment by mteodori** [comment]
cool, thank you very much for the clarification!
