### ISSUE TITLE
Invalid argument while using proxy

### ISSUE THREAD

**Issue by Tosheen** [mixpanel/mixpanel-js#330]
Hello,
We have been trying to utilize proxy for mixpanel but without success. We followed the instructions and created additional endpoint which will serve for that purpose:
`
app.use(
    "/tracking/mixpanel",
    createProxyMiddleware({
      target: "https://api.mixpanel.com",
      changeOrigin: true,
      logLevel: "silent",
    }),
  )
`
However we get an 400 as an error and the message is `
<Error>
<Code>
InvalidArgument
</Code>
<Message>
Invalid argument.
</Message>
<Details>
POST object expects Content-Type multipart/form-data
</Details>
</Error>
`
Is there anything else we need to do? Front end is of course using that endpoint as a **api_host** parameter

![mp2](https://user-images.githubusercontent.com/12643248/178992487-5d7d9661-9c25-4d17-be4f-9aee6ef2b07a.jpg)
![mp1](https://user-images.githubusercontent.com/12643248/178992492-2c67e689-d713-4a7a-ad00-879e8dc62165.jpg)
.

**Comment by tdumitrescu** [comment]
It looks like you have a custom Express proxy - which instructions are you talking about? You'll probably get better support through our normal support channels, as this issue doesn't seem to have to do with this SDK's code.

**Comment by Tosheen** [comment]
You are right.

**Comment by peterferguson** [comment]
For people who end up here in the future ... if you are in a NextJS project & you are using middleware to proxy your requests... don't. 

Use `next.config.js`

**Comment by thexpand** [comment]
What does your configuration look like @peterferguson? I can't get this to work in my Next.js project. I'm not using a middleware for the rewrites, I even have my tracking route excluded from there, but I still get the same error. Here's how the rewrites look like in my `next.config.js` file:
```js
async rewrites() {
  return [
    {
      source: '/a/lib.min.js',
      destination: 'https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js',
    },
    {
      source: '/a/lib.js',
      destination: 'https://cdn.mxpnl.com/libs/mixpanel-2-latest.js',
    },
    {
      source: '/a/decide',
      destination: 'https://decide.mixpanel.com/decide',
    },
    {
      source: '/a/:path*',
      destination: 'https://api-eu.mixpanel.com/:path*',
    },
  ];
},
```

And this is my initialization logic:
```ts
export const initializeMixpanel = (callback?: Config['loaded']) => {
  if (mixpanelToken) {
    init(mixpanelToken, {
      debug: true,
      track_pageview: true,
      persistence: 'localStorage',
      loaded: callback,
      api_host: `${isServerSide() ? process.env.SITE_URL : window.location.origin}/a`,
      api_routes: {
        track: 't',
        engage: 'e',
        groups: 'g',
      },
    });
  }
};
```
