### ISSUE TITLE
Support the $unset operation

### ISSUE THREAD

**Issue by jbwyme** [mixpanel/mixpanel-js#34]
It would be very useful to support the $unset operation in the js lib (https://mixpanel.com/help/reference/http)

**Comment by tdumitrescu** [comment]
would probably be very similar to https://github.com/mixpanel/mixpanel-js/pull/9

**Comment by ttrefren** [comment]
@jbwyme @tdumitrescu bumping this - how much work would be required?

**Comment by tdumitrescu** [comment]
This would be among the simplest of the long-overdue changes on this lib...

**Comment by tdumitrescu** [comment]
`people.unset` is now available in v2.14.0.
