### ISSUE TITLE
would be nice to expose _.info.properties

### ISSUE THREAD

**Issue by hsm3** [mixpanel/mixpanel-js#35]
I have a case where I'd like to generate some events server-side, but include as much info as possible from the user's current browser session.  Ideally I'd call mixpanel._.info.properites, pass that stuff to the server, who would then add that info to the events it later generates.  Unfortunately, that properties function's name is obfuscated by the minification.

I see that info.browser and info.device are already explicitly exempted from this obfuscation.  Why not add properties to the list, for someone who wants -all- the props?

Thanks for considering it.

**Comment by tdumitrescu** [comment]
Hi @hsm3, yeah, if you'd find it useful that'd be an easy change to make. (FWIW we don't just expose everything because it would add a lot of KB to the minified lib payload, so hearing from someone who'll actually use it is necessary first.)

CC @evnp

**Comment by tdumitrescu** [comment]
Fixed in https://github.com/mixpanel/mixpanel-js/issues/36
