### ISSUE TITLE
Access to fetch at 'https://api.mixpanel.com/track' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by SourceBoy** [mixpanel/mixpanel-js#364]
Looks like using `fetch()` from browser to send events directly to the API endpoint fails at preflight `OPTIONS` due to missing `Content-Type` from `Access-Control-Allow-Headers` from `https://api.mixpanel.com/track`

```javascript
fetch('https://api.mixpanel.com/track', {
  mode: 'cors',
  credentials: 'omit',
  cache: 'no-store',
  redirect: 'follow',
  method: 'POST',
  body: JSON.stringify({
    event: 'foo',
    properties: {
      token: 'lorem ipsum'
    }
  }),
  headers: {
    'Content-Type': 'application/json'
  }
});
```

![image](https://user-images.githubusercontent.com/791200/227687540-123d017a-f7e7-47c2-9b1d-f32a632bffc7.png)

![image](https://user-images.githubusercontent.com/791200/227687812-d1ede98b-9db9-478d-9ceb-804e20282c15.png)

**Comment by SourceBoy** [comment]
After speaking with support, using `application/x-www-form-urlencoded` with a `data` param (undocumented) works:

```javascript
const payload = {
  event: 'foobar',
  properties: {
    ..._data,
    token: 'lorem ipsum'
  }
};

const data = JSON.stringify(data);

fetch('https://api.mixpanel.com/track', {
  mode: 'cors',
  credentials: 'omit',
  cache: 'no-store',
  redirect: 'follow',
  method: 'POST',
  body: (new URLSearchParams({data})).toString(),
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded'
  }
});
```

**Comment by oguzhankoral** [comment]
I was having same problem and what you posted as support response didn't solve my problem. After a year, is there any update on this? or some documentation

**Comment by oguzhankoral** [comment]
> I was having same problem and what you posted as support response didn't solve my problem. After a year, is there any update on this? or some documentation

OK forget about what I said :) It works
