### ISSUE TITLE
How to merge two anonymous distinct_id's from different domains? Do I need to call identify, alias or merge?

### ISSUE THREAD

**Issue by oleksiy-letushev-axon** [mixpanel/mixpanel-js#369]
I have two connected websites with different domains:
- Landing Page (Webflow) - static website (has links to the main app)
- Main Single Page Application (React) - login/signup and all application functionality, which is restricted to authorized users

I need to track users beginning from the landing page:
View Landing Page -> Navigate to App -> Sign up -> Confirm email -> ...

Which method should I call to merge anonymous distinct ids from the landing page and the app?
I have this approach: In my landing page I have links to my app, e.g. `href="https://my-app"`, I added a script to set `disctinct_id` to `href` attributes via query search param, so links look like `href="https://my-app?distinct_id=123"`
Then in the main app I do the following:
```ts
mixpanel.init(TOKEN, {
   loaded: mixpanel => {
      const currentDistinctId = mixpanel.get_distinct_id()
      
      const urlParams = new URLSearchParams(window.location.search)
      const externalDistinctId = urlParams.get('distinct_id')
    
      if (externalDistinctId) {
        // identify? alias? merge?
        // mixpanel.alias(externalDistinctId, currentDistinctId)
      }
   }
})
```

I guess I need to use `merge`, but it seems like `mixpanel-browser` doesn't provide me with this method.
So what is the proper way to implement this identity management across different domains?

**Comment by tdumitrescu** [comment]
@oleksiy-letushev-axon thanks for checking in. For general implementation/identity-management questions like this, you can get personalized support from us at https://mixpanel.com/get-support or by emailing support@mixpanel.com. Someone smart and knowledgeable will get back to you quickly there!
