### ISSUE TITLE
OAuthAccountNotLinked Error when using different provider accounts with same email as EmailProvider

### ISSUE THREAD

**Issue by dlamprey** [mixpanel/mixpanel-js#376]
[DELETED]

Reported in the wrong repo. So sorry!

**Comment by tdumitrescu** [comment]
Looks like the wrong repo @dlamprey

**Comment by dlamprey** [comment]
@tdumitrescu yes, thanks for letting me know. I have no idea how that happened. So sorry.

**Comment by dlamprey** [comment]
Wrong repo.
