### ISSUE TITLE
TypeScript Error: Property 'track_pageview' does not exist on type 'OverridedMixpanel'. - v2.47.0

### ISSUE THREAD

**Issue by beforeoafterm** [mixpanel/mixpanel-js#379]
Hi, all!

I'm currently using React (`^18.1.0`) with TypeScript (`^5.0.4`) and mixpanel-browser (`^2.47.0`).

Using the new `track_pageview()` method in the latest release, however, I am encountering this TS error:

```
Property 'track_pageview' does not exist on type 'OverridedMixpanel'.
```

<img width="976" alt="Screenshot 2023-05-31 at 1 11 30 PM" src="https://github.com/mixpanel/mixpanel-js/assets/22500028/7e7ff2a0-c295-4778-8aa6-d1ea9d0296bb">

When I checked `mixpanel/index.d.ts`, it looks like the `Mixpanel` interface does not have the method signature defined for `track_pageview()`.

<img width="849" alt="Screenshot 2023-05-31 at 1 14 42 PM" src="https://github.com/mixpanel/mixpanel-js/assets/22500028/0ff86ffd-3704-44a1-a292-bf7ec9caac2a">

I believe we can fix this issue for TS users by adding the method signature:

```
track_pageview(properties?: Dict): void
```

**Comment by tdumitrescu** [comment]
It looks like these are types from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mixpanel-browser/index.d.ts. That repo would probably be the right place to submit updates.

**Comment by khanhtn91** [comment]
Same issue

**Comment by beforeoafterm** [comment]
Opened a new discussion on the DefinitelyTyped repo for this here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65666

**Comment by cotarelorodrigo** [comment]
Same problem. I need a solution to track page view in browser...

**Comment by tdumitrescu** [comment]
Looks like this was already merged? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65672

**Comment by cotarelorodrigo** [comment]
But mixpanel needs to update mixpanel-browser version?

> Looks like this was already merged? [DefinitelyTyped/DefinitelyTyped#65672](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65672)

**Comment by tdumitrescu** [comment]
> But mixpanel needs to update mixpanel-browser version?

If the new types haven't been published yet, I'd guess that's something to take up with https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by markalroberts** [comment]
Same problem - this is over a year old now? What happened?

**Comment by koooge** [comment]
It still has a problem in 2.63.0 if import like `import mixpanel from 'mixpanel-browser/src/loaders/loader-module-core'` to reduce bundle size
