### ISSUE TITLE
Documentation – outdated JavaScript example "Tracking Via Proxy"

### ISSUE THREAD

**Issue by LavransBjerkestrand** [mixpanel/mixpanel-js#397]
[Tracking Via Proxy](https://docs.mixpanel.com/docs/tracking-methods/sdks/javascript#tracking-via-proxy), api_host is not an option on Mixpanel.InitConfig. Seems to be replaced by protocol, host and path

**Comment by LavransBjerkestrand** [comment]
Oops, wrong repo

**Comment by tdumitrescu** [comment]
FWIW `api_host` is absolutely still a valid config option: https://github.com/mixpanel/mixpanel-js/blob/8ac526e5cb8563d11e2206046ab986c6491ac6d7/src/mixpanel-core.js#L88
