### ISSUE TITLE
Endpoint with track/? is not a valid URL with recent jars of spring boot 3, is there any chance to remove /  after track in mixpanel.cjs.js

### ISSUE THREAD

**Issue by nirupamab5** [mixpanel/mixpanel-js#406]
Endpoint with track/? is not a valid URL with recent spring boot 3, is there any chance to remove /  after track in URL 
form mixpanel track/ is getting added in file mixpanel.cjs.js
http://localhost:3000/sample/api/xxx/track/?ip=1&_=1700822002078

we need API url like this
http://localhost:3000/sample/api/xxx/track?ip=1&_=1700822002078

**Comment by tdumitrescu** [comment]
As of 2.48.0 you can configure the endpoints to whatever URL you like with the `api_routes` configuration option. See https://github.com/mixpanel/mixpanel-js/releases/tag/v2.48.0
