### ISSUE TITLE
`$initial_referrer` property shows up as `"$direct"`, even when it isn't

### ISSUE THREAD

**Issue by hamirmahal** [mixpanel/mixpanel-js#421]

**Comment by hamirmahal** [comment]
# Problem

[Screencast from 03-17-2024 02:47:18 PM.webm](https://github.com/mixpanel/mixpanel-js/assets/43425812/6766bbf9-dccb-4666-8773-cb6ed5e542b8)

**Comment by hamirmahal** [comment]
`$initial_referrer` and `$initial_referring_domain` should include `"github"`, no?

**Comment by hamirmahal** [comment]
# Problem

[Screencast from 03-17-2024 02:50:46 PM.webm](https://github.com/mixpanel/mixpanel-js/assets/43425812/6b0ef149-3252-4ca5-b312-55acd7b71112)

**Comment by hamirmahal** [comment]
`$initial_referrer` and `$initial_referring_domain` should include `"github"`, no?

**Comment by hamirmahal** [comment]
@tdumitrescu is this the intended behavior?

**Comment by chiyc** [comment]
Hi, @hamirmahal. It looks like in this case that the default Referrer-Policy prevents the Referer header from being sent because the browser is requesting an HTTP protocol resource from an HTTPS resource.

You can check the value of `document.referrer` in the console to confirm that the Referer value is empty. We can't determine why it's empty, so any empty value will be treated as `"$direct"`.

**Comment by hamirmahal** [comment]
Hmm... I notice this issue even when going from one HTTPS resource, https://github.com/hamirmahal/FilmFinder, to another HTTPS resource, https://hamirs-filmfinder.vercel.app/.

**Comment by hamirmahal** [comment]
How does Mixpanel recommend tracking the source of page views?

[Screencast from 05-16-2024 03:57:20 PM.webm](https://github.com/mixpanel/mixpanel-js/assets/43425812/6f29fd01-a57e-4e46-8886-43371dff475c)

**Comment by chiyc** [comment]
> Hmm... I notice this issue even when going from one HTTPS resource, https://github.com/hamirmahal/FilmFinder, to another HTTPS resource, https://hamirs-filmfinder.vercel.app/.

You'll see it's common for sites to add a "noreferrer" attribute to external links, which will also prevent the referrer from being provided. Here's the HTML for the link you clicked from GitHub where you can see that's what's happening.

```html
<a title="https://hamirs-filmfinder.vercel.app/" role="link" target="_blank" rel="noopener noreferrer nofollow" class="text-bold" href="https://hamirs-filmfinder.vercel.app/">
  hamirs-filmfinder.vercel.app/
</a>
```

> How does Mixpanel recommend tracking the source of page views?

Besides looking at referrer, the most common way to track incoming traffic sources is through UTM parameters that you add to your links. The Mixpanel SDK will pick those up and automatically add those to the page view events. So if someone visited a link such as `https://hamirs-filmfinder.vercel.app/?utm_source=github`, then our page view events will track utm_source as an event property.

**Comment by hamirmahal** [comment]
Ah, that makes sense. Thank you for the help.

**Comment by hamirmahal** [comment]
When using `utm_source` to track links to a page, I noticed that `utm_source` can stick around in the URL in the user's address bar after navigating to a page.

Is there a recommended, or industry-standard way to remove, or clean that from the URL after using `utm_source` to track where traffic came from?
