### ISSUE TITLE
Incomplete multi-character sanitization on utils.js getQueryParam function

### ISSUE THREAD

**Issue by JiatangDong** [mixpanel/mixpanel-js#443]
Our company enforced a CodeQL scan against our built bundle. And an [incomplete multi-character sanitization error](https://codeql.github.com/codeql-query-help/javascript/js-incomplete-multi-character-sanitization/) is reported from this line

https://github.com/mixpanel/mixpanel-js/blob/93df8eb5d7ada011aedb39ab723a8f415e2e5782/src/utils.js#L965

This should be easily fixed by adding a 'g' in regex

```
param = param.replace(/[[]/g, '\\[').replace(/[\]]/g, '\\]');
````

**Comment by tdumitrescu** [comment]
Thanks for the heads up. This should be fixed in release [v2.55.1](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.55.1).
