### ISSUE TITLE
Loading Mixpanel Library asynchronously

### ISSUE THREAD

**Issue by meadow-tulips** [mixpanel/mixpanel-js#456]
Is there a way we can load the Mixpanel library asynchronously using some service worker or using an async tag.. so that my initial app's first paint window time is less.

I am using nextjs (react). 

Also, can I include the `mixpanel-browser` bundle through a dynamic import and initialize the library thereafter.

**Comment by tdumitrescu** [comment]
Yes, asynchronous loading is the recommended installation path, as described here: https://docs.mixpanel.com/docs/tracking-methods/sdks/javascript#installing-the-library

"The easiest way to install the library is to load it from our CDN to your website. Paste the following code snippet right before the closing </head> tag in your page HTML."

The script tag snippet is small enough not to affect page load times meaningfully, and the full library loads asynchronously.

**Comment by meadow-tulips** [comment]
Even after adding the cdn .. am I suppose to install the mixpanel-browser package ?

The link mentions .. `import mixpanel from "mixpanel-browser";` 
and then calling init function on that.. 
Needed a little clarification here..

**Comment by meadow-tulips** [comment]
Although my function mixpanel is initialized .. I could see it in my window state.
The track events are not firing.

**Comment by meadow-tulips** [comment]
It worked mate. After I used the `mixpanel-browser` cdn link .      
I think before I was using mixpanel (node js) one .
