### ISSUE TITLE
No Github Release for 2.56.0

### ISSUE THREAD

**Issue by nightpool** [mixpanel/mixpanel-js#457]
2.56.0 seems to have been released on NPM and it's in the changelog, but there's no corresponding Github Release. This is confusing because the Github Releases page, not the CHANGELOG, is linked from the official Mixpanel docs (https://docs.mixpanel.com/docs/tracking-methods/sdks/javascript#release-history)

**Comment by tdumitrescu** [comment]
Apologies for the delay. The notes have now been published: https://github.com/mixpanel/mixpanel-js/releases/tag/v2.56.0
