### ISSUE TITLE
Missing 2.57.1 release?

### ISSUE THREAD

**Issue by nightpool** [mixpanel/mixpanel-js#462]
2.57.1 seems to have become generally available as of December 12th, but there's still no information or changelogs available for this version (No information on this repo, and no information under https://docs.mixpanel.com/docs/tracking-methods/sdks/javascript#release-history). As far as I can tell, this version does not exist.

**Comment by tdumitrescu** [comment]
This will be available shortly, thanks for your patience.

**Comment by tdumitrescu** [comment]
Release notes are up (along with 2.58.0 from today): https://github.com/mixpanel/mixpanel-js/releases
Apologies for the delay.
