### ISSUE TITLE
Missing init method option in Javascript SDK for replays

### ISSUE THREAD

**Issue by haris-syed** [mixpanel/mixpanel-js#464]
The documentation describes the `record_canvas` option as shown below [here](https://docs.mixpanel.com/docs/tracking-methods/sdks/javascript#session-replay) ![Image](https://github.com/user-attachments/assets/d8bc7904-0ba3-4470-ab37-183d966591c4)

However the option does not seem to be available in the actual method of the SDK. It is either missing altogether or the type is missing in the TS type specification.

Library versions:
"mixpanel-browser": "^2.58.0"
"@types/mixpanel-browser": "^2.50.2"

Typescript version: "^5.4.5"

**Comment by tdumitrescu** [comment]
Sorry, we don't maintain that type definition package. I believe you can find it here for issues/PRs: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mixpanel-browser/index.d.ts
