### ISSUE TITLE
retrieve / enumerate super properties?

### ISSUE THREAD

**Issue by gingerlime** [mixpanel/mixpanel-js#50]
Hi Mixpanel,

This might relate to #35, but seems slightly different. I'd like to retrieve all the super properties that we have set for a user. I can use `mixpanel.get_property`, but then I need to know the name of the super property. I couldn't find a public method exposing it.

I saw that I could access `mixpanel.persistence.props` - but feels like reaching too deep into the internals(??). Would appreciate some pointers for the recommended way of doing this.

Cheers
Yoav

**Comment by tdumitrescu** [comment]
Hi @gingerlime, `mixpanel.persistence.properties()` is a function we expose for this purpose: https://github.com/mixpanel/mixpanel-js/blob/cb67b52984cff949fb38e7eecffe0d3861215a4d/mixpanel.js#L4640

Generally anything within https://github.com/mixpanel/mixpanel-js/blob/cb67b52984cff949fb38e7eecffe0d3861215a4d/mixpanel.js#L4618-L4655 that's not underscore-prefixed is going to be available as long as we're on version 2.x of the lib (i.e. not breaking backwards compatibility).

Hope this helps!

**Comment by gingerlime** [comment]
Hey @tdumitrescu. Sorry for the late reply, but it helps a lot. I really appreciate it.
