### ISSUE TITLE
Include Mixpanel in build process

### ISSUE THREAD

**Issue by losttime** [mixpanel/mixpanel-js#55]
I would like to include mixpanel along with other 3rd party libraries in a bundle (using webpack) that is requested when my app loads. The end result will be one bundle for my app code and one bundle for my vendor code. My app will only need to load 2 JS bundles to load all the code for my app.

I am not able to run the mixpanel code with `mixpanel.js` alone. I need the snippet as well. The snippet attempts to inject an additional script on my page. Is there a supported means of bundling the mixpanel library with the bootstrapping functionality of the snippet into a single `.js` file that my app can request - even as part of a bundle with other libraries?

---

To better understand my particular situation, I am building a Chrome App. Unlike a Chrome Extension, a Chrome app cannot include external scripts, so I need to supply everything locally. My build process already bundles all my frontend JS together so I have no need for a `bower_components` or `libs` directory in my final production code. I'd like to use mixpanel without having to modify the build process to include additional stand-alone scripts.

Additionally, because this is an app that's already installed on the user's machine, I'm not concerned about network latency of downloading a large JS bundle.

**Comment by tdumitrescu** [comment]
Yup, this is coming very soon! See https://github.com/mixpanel/mixpanel-js/pull/37. The `examples` directory in that pull request include samples of how you'd load the lib with both Webpack and Browserify (the Webpack example loads the UMD build rather than CommonJS, but either one will work).

Does that look like it will do what you want?

**Comment by losttime** [comment]
Yeah, I was able to get it to work. Thanks.
