### ISSUE TITLE
Default track_pageview to false

### ISSUE THREAD

**Issue by rarkins** [mixpanel/mixpanel-js#64]
The `track_pageview` setting is true by default, but should be defaulted to false now that it's ignored in projects and pseudo-deprecated.This will suppress a lot of unnecessary `mp_page_view` events.

**Comment by tdumitrescu** [comment]
We're planning on ripping out that functionality altogether, but there are a few internal issues which need to get sorted out first. Will leave this open while we're working on it. In the meanwhile, note that our intake pipeline drops these events, so they shouldn't be affecting your analytics or data usage at least.

**Comment by mattflo-outpace** [comment]
I noticed this too. Still no movement in 3.5 years?
