### ISSUE TITLE
What should we do when a user logs out?

### ISSUE THREAD

**Issue by cerupcat** [mixpanel/mixpanel-js#67]
I've seen searching online some people use ```mixpanel.cookie.clear()``` to clear the mixpanel cookie. However, that also makes ```distinct_id``` ```undefined```. 

Is there something we should do when a user logs out or should we do nothing? I'm trying to understand the "right" behavior.

If we don't clear the cookie and the user signs up again, then two account creation events are created and both accounts associated to a single account (after aliasing). If we do clear the cookie, then there's no distinct_id (it becomes undefined) which causes issues when trying to create a new people property after a second sign up.

**Comment by jaredmixpanel** [comment]
@cerupcat check out this excellent blog post, in particular, the section "Handling Logouts on Client-side Libraries": https://mixpanel.com/blog/2015/09/21/community-tip-maintaining-user-identity

You can use the guid() function shown there to generate a new distinct_id and then call mixpanel.identify() with that value. For reseting super properties, you should call mixpanel.persistence.clear();

So the gist is, on logout...

mixpanel.persistence.clear();
mixpanel.identify(guid());  // see linked blog post for guid() function

**Comment by jaridmargolin** [comment]
So it appears both the android, and ios SDK's have `reset` methods. Is there a reason the javascript SDK does not provide this out of the box for us?

**Comment by cerupcat** [comment]
@jaredmixpanel thanks. This is helpful.

I agree with @jaredmixpanel that if there is a "correct" way of doing this, it'd be nice for the SDK to provide it to ensure that people are doing it correctly (we previously were not and therefore seeing bad reporting).

**Comment by stefansedich** [comment]
I have created a PR that should address this, I was just myself looking for a reset() method and saw that the JS SDK did not have one.

**Comment by tdumitrescu** [comment]
@cerupcat thanks to https://github.com/mixpanel/mixpanel-js/pull/71 the `reset()` method is now available in v2.8.0, much appreciated @stefansedich
