### ISSUE TITLE
Configure mixpanel to use POST?

### ISSUE THREAD

**Issue by elgerlambert** [mixpanel/mixpanel-js#76]
Hi,

Question. I'm hitting 414 uri too long errors. I was reading the docs and noticed the recommendation to POST to mixpanel's endpoints (batch documentation). As far as I can tell it's not possible to configure mixpanel to use POST as opposed to GET, is that correct?

Ideally this would be an option, if not I would like to be able to use (import/require) this lib's encoding. Is either of these options something you would consider?
Out of interest, what's the reason for preferring GET over POST - (legacy) browser support?

Kind regards

**Comment by premasagar** [comment]
I came here finding the same with the mixpanel/mixpanel-node library. Presumably it should be changed to POST.

**Comment by tdumitrescu** [comment]
Indeed, a lot of this library's code is meant to work on lowest-common-denominator browsers, and I believe in an earlier incarnation the Mixpanel HTTP API only implemented GET support for that reason. That hasn't been the case for years now, so we certainly should move to POST for XHR. We'll keep this issue open while the feature request is in the backlog. If you'd like to help expedite with a Pull Request, the relevant code is [here in the implementation of `_send_request()`](https://github.com/mixpanel/mixpanel-js/blob/f21586cf441b5461919bdba1d6257a2e9c084155/src/mixpanel-core.js#L882-L958).

**Comment by jbwyme** [comment]
Just adding a note here that this increases the chances that customers can lose autotrack data as often times the payload is larger than normal track calls.

**Comment by jack-agosthazi** [comment]
We've just run into this issue too, any update on this?

**Comment by piyushcsiitd** [comment]
https://github.com/mixpanel/mixpanel-js/pull/197

**Comment by tdumitrescu** [comment]
Resolved in [v2.32.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.32.0)
