### ISSUE TITLE
iOS 9 content blockers block events from tracking

### ISSUE THREAD

**Issue by himynameisdave** [mixpanel/mixpanel-js#79]
In iOS 9, if a user has a content-blocker installed (in my testing it was 1Blocker installed) MixPanel events will not be sent. The content-blocker will see it as a different domain and it gets blocked.

![mp-content-blocker](https://cloud.githubusercontent.com/assets/4298089/15656538/82c5b348-2676-11e6-8c6b-3f63ce601e00.png)

Unsure of how to get around this issue but this is obviously effecting a significant number of users, especially for our mobile web app.

**Comment by jaredmixpanel** [comment]
Hi @himynameisdave, unfortuantely 1Blocker and other content blockers explicitly block requests to api.mixpanel.com - the only way around this would be to proxy the calls to your own server via the mixpanel.serverURL property: https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.h#L78-L88

Or alternatively, to implement Mixpanel on your server side.

![img_1366](https://cloud.githubusercontent.com/assets/10504508/15671988/11d8621c-272e-11e6-8f99-75cdbd862844.png)

**Comment by tdumitrescu** [comment]
For the JS lib, you can set a custom tracking URL with the `api_host` config property (https://github.com/mixpanel/mixpanel-js/blob/7bf72bf4dc00e1406cc756bea675db57865cb286/src/mixpanel-core.js#L101). If you'd like more personalized guidance for your situation, I'd suggest writing in to support@mixpanel.com. We're always happy to help!

**Comment by himynameisdave** [comment]
@tdumitrescu & @jaredmixpanel thanks for the speedy reply!
