### ISSUE TITLE
Cannot read property 'disable_all_events' of undefined

### ISSUE THREAD

**Issue by FutureKode** [mixpanel/mixpanel-js#82]
Hi there,

It's possible that I am using this incorrectly but I am seeing this error: `Cannot read property 'disable_all_events' of undefined`

It looks like it is happening because I am tracking an event before init has been called. Is this allowed?

**Comment by mtzeka** [comment]
It looks like `init` is the only method exposed. Once you initialize with the appropriate parameters then all the other methods are available to use (`track`, `identify`, etc).

**Comment by tdumitrescu** [comment]
Thanks for chiming in @mtzeka. Indeed, you need to call `mixpanel.init()` with your token before doing anything else with the library.

When following the instructions at https://mixpanel.com/help/reference/javascript#installing just fill in the part that says "YOUR TOKEN" with your actually tracking token. This should go as early as possible in your page load; once that little snippet has run, you'll be able to use `mixpanel.track()` etc even before the full library has loaded and it won't block your page load either. If you need more implementation help, don't hesitate to get in touch at support@mixpanel.com.

**Comment by sblackstone** [comment]
Should anyone happen upon this, you're likely sending **null** in your call to `mixpanel.init`

**Comment by Dey-Sumit-bh** [comment]
mixpanel also provides on props named `__loaded` to check if the lib is loaded or not. Make sure the library is loaded first before firing any events.
```
const sendMixpanelEvent = (eventName: ONBOARDING_EVENT_NAME_TYPE, payload: EventPropertiesToPass) => {
    if (mixpanel.__loaded) {
      mixpanel?.track(eventName, {
        ...getEventProps(eventName, payload),
        event_timestamp: Date.now(),
      });
    }
  };
```

**Comment by tdumitrescu** [comment]
> Make sure the library is loaded first before firing any events

@Dey-Sumit-bh this isn't recommended. If you're using the asynchronous loader (the HTML snippet, i.e. the only way that `__loaded` might be false), then `mixpanel.track()` will be safe to call at any time, even before the full library has loaded, and you won't lose any data by skipping track calls.

**Comment by cfinnegan** [comment]
Hi @tdumitrescu , I'm seeing this same error on our prod env but not locally.

`Uncaught TypeError: Cannot read properties of undefined (reading 'disable_all_events')`

Any idea why this might be the case?

**Comment by sblackstone** [comment]
> Hi @tdumitrescu , I'm seeing this same error on our prod env but not locally.
> 
> `Uncaught TypeError: Cannot read properties of undefined (reading 'disable_all_events')`
> 
> Any idea why this might be the case?

Passing null into the constructor?
