### ISSUE TITLE
set_config persistence behavior

### ISSUE THREAD

**Issue by joshmatz** [mixpanel/mixpanel-js#83]
### Background
We're loading MixPanel via Segment, so we're unable configure it upon `init`, but Segment provides an [analytics.ready](https://segment.com/docs/libraries/analytics.js/#ready) function to change pulled in libraries once they're loaded.

MixPanel has a [set_config](https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.set_config) function and we're trying to use it to set `persistence` to `localStorage` instead of cookies. In this documentation, it says: 

```
  // type of persistent store for super properties (cookie/
  // localStorage) if set to "localStorage", any existing
  // mixpanel cookie value with the same persistence_name
  // will be transferred to localStorage and deleted
  persistence:                "cookie"
```

### The problem

Here's our code:

```
      window.analytics.ready(function(){
        window.mixpanel.set_config({ persistence: "localStorage", persistence_name: window.mixpanel.persistence.name || "" });
      });
```

The behavior I'm seeing is:

- The mixpanel.config object is updating as you would expect with our code.
- The existing MixPanel cookie is staying in a cookie.
- No MixPanel LocalStorage data is being added.

I'm not sure if we're doing something wrong or if the library is not working as described?

**Comment by tdumitrescu** [comment]
Sorry we missed this. The short answer is that the library currently doesn't support switching storage mechanisms midstream; if you want to use `localStorage` it needs to be configured right away in the call to `mixpanel.init`, like:
```javascript
mixpanel.init('MY TOKEN', {persistence: 'localStorage'});
```
which ensures that the lib can pull up persisted data correctly during initialization. If you need help with other implementation issues, please drop us a line at support@mixpanel.com. Thanks!

**Comment by adlerfaulkner** [comment]
It would really help if the documentation stated that the config object should be added as a parameter to the `mixpanel.init` method here [https://developer.mixpanel.com/docs/javascript-full-api-reference#mixpanelset_config](https://developer.mixpanel.com/docs/javascript-full-api-reference#mixpanelset_config) because it doesn't work if you don't know that you can use `mixpanel.set_config` after calling `mixpanel.init`.

**Comment by itsmebipul00** [comment]
Yeah it should be mentioned on docs!!
