### ISSUE TITLE
How to silence 'Refused to get unsafe header "X-MP-CE-Backoff"' warning

### ISSUE THREAD

**Issue by hraynaud** [mixpanel/mixpanel-js#92]
Recently when we run our feature specs I've noticed this error in the logs.  Any idea on how to suppress the warning or prevent it thanks.

**Comment by ilyakamens** [comment]
Hey Herby! This is unexpected behavior. I'm going to reach out to you privately so we can figure out what's going on.

**Comment by hraynaud** [comment]
@ilyakamens Thanks please ping me anytime.  I was having trouble locating the source of the message. I did a search on github for this particular header and it was only in the mixpanel js group of repositories.

**Comment by bsoule** [comment]
Did you resolve the issue? My specs have started spewing this error/warning recently as well.

**Comment by hraynaud** [comment]
@bsoule  I haven't resolved it yet. I'm still trying to clean a bunch of unrelated stuff in my test suite so I've put this off for now.  I'll get a chance to look at it over the weekend and reopen this issue when I get more details.

**Comment by hraynaud** [comment]
@bsoule @ilyakamens  I was able to resolve this issue by upgrading to the latest version of phantomJs. If you are on an older version of phantomjs < 2.1.1  that might be the issue
