### ISSUE TITLE
Failed to load mixpanel library when mixpanel.init() is called asynchronously

### ISSUE THREAD

**Issue by SummerWish** [mixpanel/mixpanel-js#93]
If `mixpanel.init()` is executed after the loading of mixpanel-core, `window.mixpanel` cannot be accessed at all, even after `mixpanel.init()` is called.

**Comment by tdumitrescu** [comment]
I think we'll need some more context to diagnose what issue you're having. How are you loading the library (via the async embed code snippet? webpack/browserify/some other commonjs-compatible loader? bower?)? If you want to show us a minimal app demonstrating your issue that could also work.

**Comment by tdumitrescu** [comment]
Going to close this out for now. Don't hesitate to re-open when you can provide some context info!
